export interface ExerciseDetail {
  name: string;
  category: string;
  image?: string; // path relative to /exercises/
  description: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  tips: string;
}

export const EXERCISE_DETAILS: Record<string, ExerciseDetail> = {
  "Bench Press": {
    name: "Bench Press",
    category: "Chest",
    image: "/exercises/bench_press.png",
    description: "The flat barbell bench press is the gold-standard compound chest exercise, building mass and strength across the pectorals, anterior deltoids, and triceps.",
    primaryMuscles: ["Pectorals (mid)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie flat on the bench with eyes under the bar. Grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it directly above your chest with arms fully extended.",
      "Lower the bar in a controlled arc to your mid-chest, keeping elbows at roughly 45–75°.",
      "Press the bar back up explosively to the starting position, exhaling at the top.",
      "Keep your feet flat on the floor and maintain a slight natural arch in your lower back.",
    ],
    tips: "Squeeze the bar hard and think about 'bending' it outward to engage your lats and keep your shoulders packed. Avoid excessive wrist extension by keeping the bar over your wrists, not your fingers.",
  },
  "Squats": {
    name: "Squats",
    category: "Legs",
    image: "/exercises/squat.png",
    description: "The barbell back squat is the king of lower-body exercises, building quad, glute, and hamstring strength while also developing core stability.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Spinal Erectors"],
    instructions: [
      "Position the bar on your upper traps (high bar) or rear delts (low bar). Step back and set feet shoulder-width apart, toes slightly out.",
      "Take a deep breath, brace your core hard, and begin the descent by pushing your knees out over your toes.",
      "Lower until your thighs are at least parallel to the floor, keeping your chest up and back neutral.",
      "Drive through your heels to stand back up, maintaining knee tracking and a neutral spine.",
      "Lock out hips and knees at the top before beginning the next rep.",
    ],
    tips: "Brace your core as if you're about to take a punch. Keep your weight distributed across the whole foot — not just the heels. If your heels rise, work on ankle mobility or use a small heel elevation.",
  },
  "Deadlifts": {
    name: "Deadlifts",
    category: "Legs",
    image: "/exercises/deadlift.png",
    description: "The conventional deadlift is a full-body hinge movement that develops posterior chain strength — hamstrings, glutes, and spinal erectors — along with grip and upper back.",
    primaryMuscles: ["Hamstrings", "Glutes", "Spinal Erectors"],
    secondaryMuscles: ["Quadriceps", "Lats", "Traps", "Forearms"],
    instructions: [
      "Stand with feet hip-width apart, bar over mid-foot. Hinge at the hips and grip the bar just outside your legs.",
      "Drop your hips, lift your chest, and create tension in your lats by 'protecting your armpits'.",
      "Push the floor away while keeping the bar close to your body — drag it up your shins.",
      "Lock out hips and knees simultaneously at the top. Stand tall, don't hyperextend.",
      "Hinge at the hips to lower the bar back to the floor under control.",
    ],
    tips: "Think 'push the floor away' rather than 'pull the bar up'. Keep the bar in contact with your legs throughout the lift to maintain a strong lever arm. Engage your lats before you pull.",
  },
  "Pull-Ups": {
    name: "Pull-Ups",
    category: "Back",
    image: "/exercises/pull_up.png",
    description: "Pull-ups are a fundamental bodyweight vertical pulling exercise that builds lat width, bicep strength, and overall upper-body pulling power.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Core"],
    instructions: [
      "Hang from the bar with an overhand grip slightly wider than shoulder-width, arms fully extended.",
      "Depress and retract your shoulder blades to initiate the pull — avoid shrugging.",
      "Pull your chest toward the bar by driving your elbows down and back.",
      "Continue until your chin clears the bar or your chest touches it.",
      "Lower yourself slowly and with control back to a full hang.",
    ],
    tips: "Initiate each rep by 'putting your shoulder blades in your back pockets' before pulling. This pre-activates the lats and protects your shoulders. Avoid kipping unless training for sport-specific reasons.",
  },
  "Barbell Rows": {
    name: "Barbell Rows",
    category: "Back",
    image: "/exercises/barbell_row.png",
    description: "The bent-over barbell row is a heavy compound back exercise that builds thickness across the mid-back, lats, and rear deltoids.",
    primaryMuscles: ["Latissimus Dorsi", "Mid Trapezius", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Spinal Erectors"],
    instructions: [
      "Stand with feet hip-width apart, hinge forward until your torso is roughly 45° to the floor.",
      "Grip the bar just outside shoulder-width. Keep your back flat and core braced.",
      "Pull the bar toward your lower chest/upper abdomen, driving your elbows back and up.",
      "Squeeze your shoulder blades together at the top of the movement.",
      "Lower the bar under control back to the starting position.",
    ],
    tips: "Keep your lower back neutral — don't round it to use more weight. Think about pulling with your elbows, not your hands, to better engage the back muscles over the biceps.",
  },
  "Overhead Press": {
    name: "Overhead Press",
    category: "Shoulders",
    image: "/exercises/overhead_press.png",
    description: "The standing barbell overhead press is the primary compound shoulder exercise, building deltoid mass and overhead pressing strength while challenging core stability.",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Trapezius", "Core"],
    instructions: [
      "Stand with feet shoulder-width apart. Hold the bar at shoulder height with an overhand grip, elbows slightly in front of the bar.",
      "Take a deep breath and brace your core and glutes to create a rigid torso.",
      "Press the bar straight up, moving your head back slightly to let the bar pass, then forward again.",
      "Lock out your elbows at the top with the bar directly over your mid-foot.",
      "Lower the bar back to shoulder height under control.",
    ],
    tips: "Squeeze your glutes and brace your abs hard to prevent lower-back hyperextension. Keep the bar path as vertical as possible. Flaring the elbows slightly forward (not fully out) is natural for most people.",
  },
  "Bicep Curls": {
    name: "Bicep Curls",
    category: "Arms",
    image: "/exercises/bicep_curl.png",
    description: "The standing dumbbell curl is the classic bicep isolation exercise, building peak and overall arm size through a full range of supinated elbow flexion.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    instructions: [
      "Stand holding dumbbells at your sides with palms facing forward (supinated grip).",
      "Keep your upper arms stationary against your torso throughout the movement.",
      "Curl the dumbbells up toward your shoulders by flexing at the elbow.",
      "Squeeze the biceps hard at the top of the movement.",
      "Lower the dumbbells slowly back to the starting position, fully extending the elbow.",
    ],
    tips: "Avoid swinging your torso to lift the weight — this transfers the load away from the biceps. Slow down the lowering phase (eccentric) for greater muscle stimulus. Supinate your wrists fully at the top for maximum bicep contraction.",
  },
  "Tricep Dips": {
    name: "Tricep Dips",
    category: "Arms",
    image: "/exercises/tricep_dip.png",
    description: "Parallel bar dips are a compound upper-body exercise that heavily loads the triceps while also engaging the chest and anterior deltoids.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectorals", "Anterior Deltoids"],
    instructions: [
      "Grip the parallel bars and push yourself up to a straight-arm support position.",
      "Lean your torso slightly forward to shift emphasis toward the triceps.",
      "Lower your body by bending your elbows, keeping them close to your sides.",
      "Descend until your upper arms are roughly parallel to the floor.",
      "Press back up to the starting position by extending your elbows fully.",
    ],
    tips: "Keeping your torso more upright and elbows tucked close to your sides maximises tricep activation. Leaning forward too much shifts the load to the chest. Add weight with a dip belt once bodyweight becomes easy.",
  },
  "Lat Pulldowns": {
    name: "Lat Pulldowns",
    category: "Back",
    image: "/exercises/lat_pulldown.png",
    description: "The lat pulldown is a cable-based vertical pulling exercise that builds lat width and is an excellent progression tool toward unassisted pull-ups.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Teres Major"],
    instructions: [
      "Sit at the lat pulldown machine and secure your thighs under the pads. Grip the bar wider than shoulder-width.",
      "Lean back slightly (about 10–15°) and depress your shoulder blades.",
      "Pull the bar down toward your upper chest by driving your elbows down and back.",
      "Squeeze your lats at the bottom of the movement.",
      "Allow the bar to rise slowly back to the starting position with arms fully extended.",
    ],
    tips: "Think about pulling your elbows to your hip pockets rather than pulling the bar down. Avoid using momentum or excessive body sway. A full stretch at the top of each rep maximises the range of motion.",
  },
  "Leg Press": {
    name: "Leg Press",
    category: "Legs",
    image: "/exercises/leg_press.png",
    description: "The leg press machine allows heavy quad-dominant loading with reduced spinal stress, making it an excellent complement to free-weight squatting.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    instructions: [
      "Sit in the leg press machine with your back flat against the pad. Place feet shoulder-width apart on the footplate.",
      "Release the safety handles and lower the platform by bending your knees toward your chest.",
      "Descend until your knees are at roughly 90° or slightly below, keeping your lower back flat.",
      "Press the platform away by extending your knees and hips simultaneously.",
      "Lock out your legs at the top but avoid hyperextending the knees.",
    ],
    tips: "Never allow your lower back to round off the pad — this puts dangerous stress on the lumbar spine. Higher foot placement emphasises glutes and hamstrings; lower placement emphasises quads. Don't lock out aggressively.",
  },
  "Romanian Deadlifts": {
    name: "Romanian Deadlifts",
    category: "Legs",
    image: "/exercises/romanian_deadlift.png",
    description: "The Romanian deadlift is a hip-hinge movement that targets the hamstrings and glutes through a long range of motion, building posterior chain strength and flexibility.",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Spinal Erectors", "Adductors"],
    instructions: [
      "Stand holding a barbell at hip height with an overhand grip, feet hip-width apart.",
      "Push your hips back while maintaining a flat back, lowering the bar along your legs.",
      "Feel a deep stretch in your hamstrings — typically the bar reaches mid-shin level.",
      "Drive your hips forward to return to the starting position, squeezing your glutes at the top.",
      "Keep the bar close to your body throughout the entire movement.",
    ],
    tips: "The movement is initiated by pushing your hips backward, not by bending your knees. Maintain a slight bend in the knees throughout. If you feel it more in your lower back than your hamstrings, you're likely rounding your spine.",
  },
  "Incline Bench Press": {
    name: "Incline Bench Press",
    category: "Chest",
    image: "/exercises/incline_bench_press.png",
    description: "The incline barbell bench press targets the upper portion of the pectorals and anterior deltoids, building a fuller, more developed upper chest.",
    primaryMuscles: ["Upper Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Set the bench to a 30–45° incline. Lie back and grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it above your upper chest with arms extended.",
      "Lower the bar to your upper chest (below your clavicle) in a controlled arc.",
      "Press the bar back up to the starting position, exhaling as you push.",
      "Keep your feet flat on the floor and shoulder blades retracted throughout.",
    ],
    tips: "A 30° incline hits the upper chest more effectively than a steeper angle, which starts to shift the load to the shoulders. Keep the bar path slightly back toward the rack at the top to maintain shoulder safety.",
  },
  "Dumbbell Rows": {
    name: "Dumbbell Rows",
    category: "Back",
    image: "/exercises/dumbbell_row.png",
    description: "The single-arm dumbbell row allows a greater range of motion than barbell rows and helps correct left-right strength imbalances in the back.",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Teres Major"],
    instructions: [
      "Place one knee and the same-side hand on a flat bench for support. Hold a dumbbell in the other hand.",
      "Let the dumbbell hang straight down with your arm fully extended and back flat.",
      "Pull the dumbbell up toward your hip, driving your elbow back and up.",
      "Squeeze your lat and rhomboid at the top of the movement.",
      "Lower the dumbbell slowly back to the starting position.",
    ],
    tips: "Think about pulling your elbow to the ceiling rather than pulling the dumbbell up. Allow a slight rotation of the torso at the top to get a full contraction. Keep your lower back neutral throughout.",
  },
  "Shoulder Press": {
    name: "Shoulder Press",
    category: "Shoulders",
    image: "/exercises/shoulder_press.png",
    description: "The seated dumbbell shoulder press builds deltoid mass and overhead strength while allowing a more natural wrist and elbow path compared to the barbell version.",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Trapezius"],
    instructions: [
      "Sit on an upright bench with back support. Hold dumbbells at shoulder height, palms facing forward.",
      "Press the dumbbells overhead in an arc, bringing them together at the top.",
      "Lock out your elbows at the top without letting the dumbbells touch.",
      "Lower the dumbbells back to shoulder height in a controlled manner.",
      "Keep your core braced and avoid arching your lower back excessively.",
    ],
    tips: "Avoid pressing straight up and then letting the dumbbells drift forward — keep them in line with your ears throughout. Using a slight neutral grip (palms facing each other) can reduce shoulder impingement risk.",
  },
  "Lunges": {
    name: "Lunges",
    category: "Legs",
    image: "/exercises/lunges.png",
    description: "Dumbbell lunges are a unilateral leg exercise that builds quad and glute strength while improving balance, coordination, and hip flexibility.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    instructions: [
      "Stand holding dumbbells at your sides, feet together.",
      "Step forward with one foot, landing with your heel first.",
      "Lower your back knee toward the floor, keeping your front shin vertical.",
      "Your front thigh should be parallel to the floor at the bottom.",
      "Push through your front heel to return to the starting position, then alternate legs.",
    ],
    tips: "Keep your torso upright throughout — avoid leaning forward. The front knee should track over your second toe, not cave inward. Start with bodyweight to master the movement pattern before adding load.",
  },
  "Leg Curls": {
    name: "Leg Curls",
    category: "Legs",
    image: "/exercises/leg_curl.png",
    description: "The lying leg curl is the primary hamstring isolation exercise, targeting the biceps femoris, semitendinosus, and semimembranosus through knee flexion.",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Gastrocnemius"],
    instructions: [
      "Lie face down on the leg curl machine with the padded roller just above your heels.",
      "Grip the handles for stability and keep your hips pressed into the pad.",
      "Curl your legs up toward your glutes by flexing at the knee.",
      "Squeeze your hamstrings hard at the top of the movement.",
      "Lower your legs slowly back to the starting position — don't let the weight drop.",
    ],
    tips: "Plantarflexing your feet (pointing toes) at the top of the movement increases hamstring activation. Avoid lifting your hips off the pad, as this reduces the range of motion and shifts load away from the hamstrings.",
  },
  "Leg Extensions": {
    name: "Leg Extensions",
    category: "Legs",
    image: "/exercises/leg_extension.png",
    description: "The leg extension is a quad isolation exercise performed on a machine, targeting the rectus femoris and vastus muscles through knee extension.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    instructions: [
      "Sit on the leg extension machine with your back against the pad and knees at the edge of the seat.",
      "Position the padded roller just above your ankles.",
      "Extend your legs by straightening your knees until your legs are parallel to the floor.",
      "Squeeze your quads hard at the top of the movement.",
      "Lower the weight slowly back to the starting position.",
    ],
    tips: "Avoid using excessive weight that causes your hips to lift off the seat. Slow, controlled reps with a peak contraction at the top are more effective than heavy, momentum-driven reps. Some people find a slight toe-in or toe-out position more comfortable.",
  },
  "Calf Raises": {
    name: "Calf Raises",
    category: "Legs",
    image: "/exercises/calf_raise.png",
    description: "Standing calf raises target the gastrocnemius through plantar flexion, building calf size and lower-leg strength.",
    primaryMuscles: ["Gastrocnemius"],
    secondaryMuscles: ["Soleus"],
    instructions: [
      "Stand on the edge of a step or calf raise platform with the balls of your feet on the edge.",
      "Let your heels drop below the step level for a full stretch.",
      "Rise up onto the balls of your feet as high as possible.",
      "Hold the peak contraction for a moment before lowering.",
      "Lower your heels back below the step level for a full stretch on each rep.",
    ],
    tips: "The calves respond well to high reps and a full range of motion. Pause at the bottom for a true stretch and at the top for a full contraction. Avoid bouncing through the movement — control every rep.",
  },
  "Chest Flyes": {
    name: "Chest Flyes",
    category: "Chest",
    image: "/exercises/chest_fly.png",
    description: "Dumbbell chest flyes isolate the pectorals through a wide arc of shoulder horizontal adduction, providing a deep stretch and strong peak contraction.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Lie flat on a bench holding dumbbells above your chest, palms facing each other, elbows slightly bent.",
      "Lower the dumbbells in a wide arc out to your sides, maintaining the slight elbow bend.",
      "Feel a deep stretch across your chest at the bottom of the movement.",
      "Bring the dumbbells back together in the same arc, squeezing your chest at the top.",
      "Do not straighten your elbows — keep them slightly bent throughout.",
    ],
    tips: "Think about hugging a large tree — the movement is a wide arc, not a press. Keep the elbows at a fixed angle throughout. Go lighter than you think you need to; this is an isolation exercise, not a strength movement.",
  },
  "Lateral Raises": {
    name: "Lateral Raises",
    category: "Shoulders",
    image: "/exercises/lateral_raise.png",
    description: "Dumbbell lateral raises isolate the lateral deltoid head, which is primarily responsible for shoulder width and the coveted 'capped' shoulder look.",
    primaryMuscles: ["Lateral Deltoids"],
    secondaryMuscles: ["Anterior Deltoids", "Upper Trapezius"],
    instructions: [
      "Stand holding dumbbells at your sides with a slight bend in your elbows.",
      "Raise both arms out to the sides simultaneously, leading with your elbows.",
      "Lift until your arms are parallel to the floor (shoulder height).",
      "Hold briefly at the top, then lower the dumbbells slowly back to your sides.",
      "Avoid shrugging your shoulders or using momentum.",
    ],
    tips: "Tilt the dumbbells slightly so the front is a little lower than the back (like pouring a jug) — this internally rotates the shoulder and maximises lateral delt activation. Use light weight and focus on the muscle contraction over load.",
  },
  "Front Raises": {
    name: "Front Raises",
    category: "Shoulders",
    image: "/exercises/front_raise.png",
    description: "Dumbbell front raises isolate the anterior deltoid head through shoulder flexion, complementing pressing movements for complete front delt development.",
    primaryMuscles: ["Anterior Deltoids"],
    secondaryMuscles: ["Lateral Deltoids", "Upper Pectorals"],
    instructions: [
      "Stand holding dumbbells in front of your thighs, palms facing your body.",
      "Raise both arms forward and upward with a slight bend in the elbows.",
      "Lift until your arms are parallel to the floor or slightly above.",
      "Hold briefly at the top, then lower the dumbbells slowly back to the starting position.",
      "Keep your torso still — avoid swinging to generate momentum.",
    ],
    tips: "The anterior deltoid is already heavily worked in pressing movements, so front raises are best used as a finishing exercise with moderate weight. Alternate arms to increase time under tension and control.",
  },
  "Hammer Curls": {
    name: "Hammer Curls",
    category: "Arms",
    image: "/exercises/hammer_curl.png",
    description: "Hammer curls use a neutral (thumbs-up) grip to emphasise the brachialis and brachioradialis alongside the biceps, building arm thickness and forearm strength.",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps Brachii"],
    instructions: [
      "Stand holding dumbbells at your sides with a neutral grip (palms facing your body).",
      "Keep your upper arms stationary and curl both dumbbells up simultaneously.",
      "Lift until your thumbs are near your shoulders.",
      "Squeeze at the top, then lower slowly back to the starting position.",
      "Maintain the neutral grip throughout — do not rotate your wrists.",
    ],
    tips: "The brachialis lies underneath the biceps and when developed pushes the biceps up, creating a larger arm appearance. Hammer curls are one of the best exercises to target it. Alternate arms to focus on each side.",
  },
  "Tricep Extensions": {
    name: "Tricep Extensions",
    category: "Arms",
    image: "/exercises/tricep_extension.png",
    description: "The overhead dumbbell tricep extension targets the long head of the triceps — the largest portion — through a full overhead range of motion.",
    primaryMuscles: ["Triceps Brachii (long head)"],
    secondaryMuscles: ["Triceps Brachii (lateral & medial heads)"],
    instructions: [
      "Sit on a bench and hold a single dumbbell with both hands, palms cupping the top plate.",
      "Press the dumbbell overhead until your arms are fully extended.",
      "Lower the dumbbell behind your head by bending your elbows, keeping them pointing straight up.",
      "Descend until you feel a full stretch in your triceps.",
      "Extend your elbows to press the dumbbell back to the starting position.",
    ],
    tips: "The overhead position stretches the long head of the triceps maximally, making this one of the most effective tricep exercises for mass. Keep your elbows close together and pointing straight up — don't let them flare out.",
  },
  "Face Pulls": {
    name: "Face Pulls",
    category: "Shoulders",
    image: "/exercises/face_pull.png",
    description: "Face pulls target the rear deltoids and external rotators of the shoulder, improving posture, shoulder health, and posterior delt development.",
    primaryMuscles: ["Rear Deltoids"],
    secondaryMuscles: ["External Rotators", "Mid Trapezius", "Rhomboids"],
    instructions: [
      "Set a cable machine to upper-chest height and attach a rope. Grip the rope with both hands, thumbs facing you.",
      "Step back until there is tension in the cable. Stand with feet shoulder-width apart.",
      "Pull the rope toward your face, separating your hands and flaring your elbows out to the sides.",
      "Aim to pull your hands to either side of your face with elbows at shoulder height.",
      "Hold briefly at the peak contraction, then return slowly to the starting position.",
    ],
    tips: "Face pulls are one of the best exercises for shoulder health and posture correction. Focus on the external rotation component — pulling your hands apart at the end of the movement. Use a weight that allows full range of motion.",
  },
  "Cable Rows": {
    name: "Cable Rows",
    category: "Back",
    image: "/exercises/cable_row.png",
    description: "The seated cable row provides constant tension throughout the range of motion, building mid-back thickness and improving posture through horizontal pulling.",
    primaryMuscles: ["Mid Trapezius", "Rhomboids", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    instructions: [
      "Sit at the cable row machine with feet on the footrests and knees slightly bent.",
      "Grip the handle with both hands, arms extended, and sit up tall with a flat back.",
      "Pull the handle toward your lower abdomen by driving your elbows back.",
      "Squeeze your shoulder blades together at the end of the pull.",
      "Extend your arms slowly back to the starting position, allowing a slight forward lean for a full stretch.",
    ],
    tips: "Avoid rounding your lower back or using excessive body sway. The slight forward lean at the start of each rep (not a full hinge) allows a greater range of motion and better lat stretch. Keep your chest up throughout.",
  },
  "Preacher Curls": {
    name: "Preacher Curls",
    category: "Arms",
    image: "/exercises/preacher_curl.png",
    description: "The preacher curl isolates the biceps by eliminating shoulder flexion cheating, providing a unique stretch at the bottom and peak contraction at the top.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis"],
    instructions: [
      "Sit at the preacher curl bench and place your upper arms flat on the angled pad.",
      "Grip the barbell or EZ-bar with an underhand grip at the bottom of the movement.",
      "Curl the bar upward by flexing your elbows, keeping your upper arms on the pad.",
      "Squeeze your biceps hard at the top.",
      "Lower the bar slowly back to the fully extended position — don't let it drop.",
    ],
    tips: "The bottom position (full extension) is where the biceps are most stretched and most vulnerable. Control the lowering phase carefully. Avoid locking out aggressively at the bottom as this can stress the elbow joint.",
  },
  "Skull Crushers": {
    name: "Skull Crushers",
    category: "Arms",
    image: "/exercises/skull_crusher.png",
    description: "Skull crushers (lying tricep extensions) are a compound tricep exercise that loads all three heads of the triceps through elbow extension.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Lie flat on a bench and hold a barbell or EZ-bar with arms extended straight up above your chest.",
      "Keep your upper arms perpendicular to the floor and stationary throughout.",
      "Lower the bar toward your forehead by bending your elbows.",
      "Stop just before the bar reaches your forehead, then extend your elbows to press back up.",
      "Keep the movement slow and controlled, especially on the lowering phase.",
    ],
    tips: "Despite the name, the bar should travel toward your forehead, not your skull. Some lifters find lowering slightly behind the head (to the forehead/top of head) provides a better stretch. Use an EZ-bar to reduce wrist strain.",
  },
  "Hip Thrusts": {
    name: "Hip Thrusts",
    category: "Legs",
    image: "/exercises/hip_thrust.png",
    description: "The barbell hip thrust is the most effective glute isolation exercise, providing peak glute activation at the top of the movement through hip extension.",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    instructions: [
      "Sit on the floor with your upper back against a bench and a barbell across your hips.",
      "Plant your feet flat on the floor, hip-width apart, toes slightly out.",
      "Drive through your heels to thrust your hips upward, squeezing your glutes hard.",
      "At the top, your torso should be parallel to the floor and shins vertical.",
      "Lower your hips back to the floor under control and repeat.",
    ],
    tips: "The key to maximising glute activation is a full hip extension at the top with a strong glute squeeze. Use a barbell pad for comfort. Avoid hyperextending your lower back — the movement comes from the hips, not the spine.",
  },
  "Planks": {
    name: "Planks",
    category: "Core",
    image: "/exercises/plank.png",
    description: "The forearm plank is a fundamental core stability exercise that builds isometric strength in the abs, obliques, and spinal stabilisers.",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Obliques", "Spinal Erectors", "Glutes", "Shoulders"],
    instructions: [
      "Start in a push-up position, then lower onto your forearms with elbows directly under your shoulders.",
      "Form a straight line from your head to your heels — no sagging hips or raised buttocks.",
      "Brace your core as if bracing for a punch, and squeeze your glutes.",
      "Keep your neck neutral — look at the floor just in front of your hands.",
      "Hold the position for the desired duration, breathing steadily.",
    ],
    tips: "Quality beats quantity — a 30-second plank with perfect form is more beneficial than a 2-minute plank with a sagging back. Focus on creating full-body tension: squeeze your fists, glutes, and abs simultaneously.",
  },
  "Russian Twists": {
    name: "Russian Twists",
    category: "Core",
    image: "/exercises/russian_twist.png",
    description: "Russian twists are a rotational core exercise that targets the obliques and builds rotational strength and stability.",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Rectus Abdominis", "Hip Flexors"],
    instructions: [
      "Sit on the floor with knees bent and feet slightly raised or flat on the floor.",
      "Lean your torso back to approximately 45°, keeping your back straight.",
      "Hold a weight plate, dumbbell, or medicine ball with both hands in front of your chest.",
      "Rotate your torso to one side, bringing the weight toward the floor beside your hip.",
      "Rotate to the other side in a controlled manner, completing one full rep.",
    ],
    tips: "The rotation should come from your torso, not just your arms. Keep your chest up and avoid rounding your lower back. Elevating your feet increases the difficulty by removing a base of support. Move slowly and deliberately.",
  },
  // Additional exercises with images from the library
  "Incline Press": {
    name: "Incline Press",
    category: "Chest",
    image: "/exercises/incline_press.png",
    description: "The incline dumbbell press targets the upper chest and anterior deltoids, building a fuller upper pectoral region.",
    primaryMuscles: ["Upper Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Set a bench to 30–45°. Sit back holding dumbbells at shoulder height, palms forward.",
      "Press the dumbbells upward and slightly inward until arms are extended.",
      "Lower the dumbbells back to chest level in a controlled arc.",
      "Keep your shoulder blades retracted and back against the bench.",
    ],
    tips: "A 30° angle is optimal for upper chest activation without shifting too much load to the shoulders. Keep the dumbbells in line with your upper chest throughout.",
  },
  "Dumbbell Press": {
    name: "Dumbbell Press",
    category: "Chest",
    image: "/exercises/dumbbell_press.png",
    description: "The flat dumbbell press allows a greater range of motion than the barbell bench press and helps correct strength imbalances between sides.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie flat on a bench holding dumbbells at chest height, palms facing forward.",
      "Press the dumbbells upward until arms are fully extended.",
      "Lower the dumbbells to chest level in a controlled arc.",
      "Keep your feet flat on the floor and back slightly arched.",
    ],
    tips: "Allow the dumbbells to travel slightly wider than the barbell path for a better chest stretch. Squeeze the dumbbells together at the top to maximise pectoral contraction.",
  },
  "Dumbbell Fly": {
    name: "Dumbbell Fly",
    category: "Chest",
    image: "/exercises/dumbbell_fly.png",
    description: "The dumbbell fly isolates the pectorals through a wide arc of shoulder horizontal adduction, providing a deep stretch.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Lie flat on a bench with dumbbells above your chest, palms facing each other.",
      "Lower the dumbbells in a wide arc with a slight elbow bend.",
      "Feel a deep chest stretch at the bottom.",
      "Bring the dumbbells back together in the same arc.",
    ],
    tips: "Keep a fixed elbow angle throughout. This is an isolation exercise — use moderate weight and focus on the stretch and squeeze.",
  },
  "Cable Fly (High-to-Low)": {
    name: "Cable Fly (High-to-Low)",
    category: "Chest",
    image: "/exercises/cable_fly.png",
    description: "The high-to-low cable fly targets the lower pectorals with constant cable tension throughout the movement.",
    primaryMuscles: ["Lower Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Set cables to the highest position. Stand in the middle and grip one handle in each hand.",
      "Step forward slightly and lean forward from the hips.",
      "Bring your hands together in a downward arc in front of your lower abdomen.",
      "Squeeze your chest at the bottom, then return slowly.",
    ],
    tips: "The cable provides constant tension unlike dumbbells. Focus on the squeeze at the bottom of each rep.",
  },
  "Skullcrushers": {
    name: "Skullcrushers",
    category: "Arms",
    image: "/exercises/skullcrusher.png",
    description: "Skullcrushers are a lying tricep extension that loads all three heads of the triceps through elbow extension.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Lie on a bench with an EZ-bar or barbell held above your chest, arms extended.",
      "Lower the bar toward your forehead by bending only at the elbows.",
      "Extend your elbows to press back to the starting position.",
    ],
    tips: "Keep your upper arms perpendicular to the floor. Use an EZ-bar to reduce wrist strain.",
  },
  "Rope Pushdowns": {
    name: "Rope Pushdowns",
    category: "Arms",
    image: "/exercises/rope_pushdown.png",
    description: "Cable rope pushdowns isolate the triceps with constant tension, and the rope allows a wider range of motion at the bottom.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Attach a rope to a high cable pulley. Stand facing the machine and grip the rope with both hands.",
      "Keep your upper arms against your sides and push the rope down.",
      "At the bottom, spread the rope ends apart to maximise the contraction.",
      "Return slowly to the starting position.",
    ],
    tips: "Flaring the rope ends outward at the bottom increases lateral head activation. Keep your elbows tucked in throughout.",
  },
  "Bulgarian Split Squats": {
    name: "Bulgarian Split Squats",
    category: "Legs",
    image: "/exercises/bulgarian_split_squat.png",
    description: "The Bulgarian split squat is a demanding unilateral leg exercise that builds quad and glute strength while improving hip mobility.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    instructions: [
      "Stand in front of a bench and place your rear foot on it, laces down.",
      "Step your front foot forward far enough that your shin stays vertical when you descend.",
      "Lower your back knee toward the floor, keeping your torso upright.",
      "Drive through your front heel to return to the starting position.",
    ],
    tips: "This exercise is notoriously difficult. Start with bodyweight to master the balance before adding load. A longer front foot position emphasises the glutes; shorter emphasises the quads.",
  },
  "Hanging Leg Raises": {
    name: "Hanging Leg Raises",
    category: "Core",
    image: "/exercises/hanging_leg_raise.png",
    description: "Hanging leg raises build lower abdominal strength and hip flexor endurance through a full range of hip flexion while hanging from a bar.",
    primaryMuscles: ["Lower Rectus Abdominis", "Hip Flexors"],
    secondaryMuscles: ["Obliques", "Grip Strength"],
    instructions: [
      "Hang from a pull-up bar with an overhand grip, arms fully extended.",
      "Brace your core and raise your legs by flexing your hips and knees.",
      "Lift until your thighs are at least parallel to the floor, or higher for more difficulty.",
      "Lower your legs slowly back to the starting position.",
    ],
    tips: "Avoid swinging — control the movement throughout. For more difficulty, keep your legs straight. Focus on posterior pelvic tilt at the top to maximise lower ab activation.",
  },
  "Ab Wheel": {
    name: "Ab Wheel",
    category: "Core",
    image: "/exercises/ab_wheel.png",
    description: "The ab wheel rollout is one of the most demanding core exercises, building anti-extension core strength through a long lever arm.",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Obliques", "Lats", "Shoulders"],
    instructions: [
      "Kneel on the floor and grip the ab wheel handles with both hands.",
      "Start with the wheel directly under your shoulders.",
      "Roll the wheel forward, extending your body as far as you can while keeping your back flat.",
      "Contract your core to pull the wheel back to the starting position.",
    ],
    tips: "Start with partial rollouts if you cannot complete a full rollout with a neutral spine. Never let your lower back sag — this is a core stability exercise, not a hip flexor exercise.",
  },
  "Running": {
    name: "Running",
    category: "Cardio",
    image: "/exercises/running.png",
    description: "Running is the most accessible cardio exercise, improving cardiovascular fitness, endurance, and caloric expenditure.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    instructions: [
      "Start with a 5-minute warm-up walk before increasing to your target pace.",
      "Maintain an upright posture with a slight forward lean from the ankles.",
      "Land with your foot under your centre of mass, not out in front.",
      "Keep your arms relaxed at roughly 90° and swing them forward-backward, not across your body.",
      "Cool down with a 5-minute walk and stretch afterward.",
    ],
    tips: "For beginners, use a run/walk interval approach (e.g., 1 min run, 2 min walk) and gradually increase running time. Proper footwear is essential to prevent injury. Track your pace and aim for conversational effort on easy days.",
  },
  "Jump Rope": {
    name: "Jump Rope",
    category: "Cardio",
    image: "/exercises/jump_rope.png",
    description: "Jump rope is a high-intensity cardio exercise that builds coordination, footwork, and cardiovascular fitness.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Calves", "Shoulders", "Core"],
    instructions: [
      "Hold the rope handles at hip height with elbows close to your sides.",
      "Start with small wrist rotations to swing the rope over your head.",
      "Jump with both feet together, clearing the rope by just a few centimetres.",
      "Land softly on the balls of your feet with knees slightly bent.",
      "Maintain a steady rhythm and keep your core engaged.",
    ],
    tips: "Start with basic two-foot jumps before progressing to alternating feet or double-unders. Jump on a forgiving surface like a rubber mat. Keep jumps low and efficient — you only need to clear the rope.",
  },
};

/**
 * Aliases: maps exercise names from exercises.ts to keys in EXERCISE_DETAILS
 */
const EXERCISE_ALIASES: Record<string, string> = {
  // Back
  "Lat Pulldown": "Lat Pulldowns",
  "Seated Cable Row": "Cable Rows",
  // Chest
  "Chest Flyes": "Chest Flyes",
  "Incline Bench Press": "Incline Bench Press",
  // Arms
  "Skull Crushers": "Skull Crushers",
  "Tricep Extensions": "Tricep Extensions",
  // Legs
  "Leg Extensions": "Leg Extensions",
  "Calf Raises": "Calf Raises",
  "Standing Calf Raises": "Calf Raises",
  "Seated Calf Raises": "Calf Raises",
  // Shoulders
  "Lateral Raise": "Lateral Raises",
  "Front Raise": "Front Raises",
  "Overhead Press": "Overhead Press",
  // Core
  "Plank": "Planks",
  "Russian Twist": "Russian Twists",
  "Hanging Leg Raise": "Hanging Leg Raises",
};

/**
 * Get exercise detail by exercise name (case-insensitive, alias-aware)
 */
export function getExerciseDetail(name: string): ExerciseDetail | undefined {
  // Exact match first
  if (EXERCISE_DETAILS[name]) return EXERCISE_DETAILS[name];
  // Alias match
  const aliasKey = EXERCISE_ALIASES[name];
  if (aliasKey && EXERCISE_DETAILS[aliasKey]) return EXERCISE_DETAILS[aliasKey];
  // Case-insensitive match
  const lower = name.toLowerCase();
  const key = Object.keys(EXERCISE_DETAILS).find(k => k.toLowerCase() === lower);
  if (key) return EXERCISE_DETAILS[key];
  // Case-insensitive alias match
  const aliasKeyCI = Object.keys(EXERCISE_ALIASES).find(k => k.toLowerCase() === lower);
  if (aliasKeyCI) {
    const resolved = EXERCISE_ALIASES[aliasKeyCI];
    if (EXERCISE_DETAILS[resolved]) return EXERCISE_DETAILS[resolved];
  }
  return undefined;
}
