export interface ExerciseDetail {
  name: string;
  category: string;
  image?: string; // path relative to /exercises/
  description: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  tips: string;
}

export const EXERCISE_DETAILS: Record<string, ExerciseDetail> = {
  "Bench Press": {
    name: "Bench Press",
    category: "Chest",
    image: "/exercises/bench_press.webp",
    description: "The flat barbell bench press is the gold-standard compound chest exercise, building mass and strength across the pectorals, anterior deltoids, and triceps.",
    primaryMuscles: ["Pectorals (mid)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie flat on the bench with eyes under the bar. Grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it directly above your chest with arms fully extended.",
      "Lower the bar in a controlled arc to your mid-chest, keeping elbows at roughly 45–75°.",
      "Press the bar back up explosively to the starting position, exhaling at the top.",
      "Keep your feet flat on the floor and maintain a slight natural arch in your lower back.",
    ],
    tips: "Squeeze the bar hard and think about 'bending' it outward to engage your lats and keep your shoulders packed. Avoid excessive wrist extension by keeping the bar over your wrists, not your fingers.",
  },
  "Squats": {
    name: "Squats",
    category: "Legs",
    image: "/exercises/squat.webp",
    description: "The barbell back squat is the king of lower-body exercises, building quad, glute, and hamstring strength while also developing core stability.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Spinal Erectors"],
    instructions: [
      "Position the bar on your upper traps (high bar) or rear delts (low bar). Step back and set feet shoulder-width apart, toes slightly out.",
      "Take a deep breath, brace your core hard, and begin the descent by pushing your knees out over your toes.",
      "Lower until your thighs are at least parallel to the floor, keeping your chest up and back neutral.",
      "Drive through your heels to stand back up, maintaining knee tracking and a neutral spine.",
      "Lock out hips and knees at the top before beginning the next rep.",
    ],
    tips: "Brace your core as if you're about to take a punch. Keep your weight distributed across the whole foot — not just the heels. If your heels rise, work on ankle mobility or use a small heel elevation.",
  },
  "Deadlifts": {
    name: "Deadlifts",
    category: "Legs",
    image: "/exercises/deadlift.webp",
    description: "The conventional deadlift is a full-body hinge movement that develops posterior chain strength — hamstrings, glutes, and spinal erectors — along with grip and upper back.",
    primaryMuscles: ["Hamstrings", "Glutes", "Spinal Erectors"],
    secondaryMuscles: ["Quadriceps", "Lats", "Traps", "Forearms"],
    instructions: [
      "Stand with feet hip-width apart, bar over mid-foot. Hinge at the hips and grip the bar just outside your legs.",
      "Drop your hips, lift your chest, and create tension in your lats by 'protecting your armpits'.",
      "Push the floor away while keeping the bar close to your body — drag it up your shins.",
      "Lock out hips and knees simultaneously at the top. Stand tall, don't hyperextend.",
      "Hinge at the hips to lower the bar back to the floor under control.",
    ],
    tips: "Think 'push the floor away' rather than 'pull the bar up'. Keep the bar in contact with your legs throughout the lift to maintain a strong lever arm. Engage your lats before you pull.",
  },
  "Pull-Ups": {
    name: "Pull-Ups",
    category: "Back",
    image: "/exercises/pull_up.webp",
    description: "Pull-ups are a fundamental bodyweight vertical pulling exercise that builds lat width, bicep strength, and overall upper-body pulling power.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Core"],
    instructions: [
      "Hang from the bar with an overhand grip slightly wider than shoulder-width, arms fully extended.",
      "Depress and retract your shoulder blades to initiate the pull — avoid shrugging.",
      "Pull your chest toward the bar by driving your elbows down and back.",
      "Continue until your chin clears the bar or your chest touches it.",
      "Lower yourself slowly and with control back to a full hang.",
    ],
    tips: "Initiate each rep by 'putting your shoulder blades in your back pockets' before pulling. This pre-activates the lats and protects your shoulders. Avoid kipping unless training for sport-specific reasons.",
  },
  "Barbell Rows": {
    name: "Barbell Rows",
    category: "Back",
    image: "/exercises/barbell_row.webp",
    description: "The bent-over barbell row is a heavy compound back exercise that builds thickness across the mid-back, lats, and rear deltoids.",
    primaryMuscles: ["Latissimus Dorsi", "Mid Trapezius", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Spinal Erectors"],
    instructions: [
      "Stand with feet hip-width apart, hinge forward until your torso is roughly 45° to the floor.",
      "Grip the bar just outside shoulder-width. Keep your back flat and core braced.",
      "Pull the bar toward your lower chest/upper abdomen, driving your elbows back and up.",
      "Squeeze your shoulder blades together at the top of the movement.",
      "Lower the bar under control back to the starting position.",
    ],
    tips: "Keep your lower back neutral — don't round it to use more weight. Think about pulling with your elbows, not your hands, to better engage the back muscles over the biceps.",
  },
  "Overhead Press": {
    name: "Overhead Press",
    category: "Shoulders",
    image: "/exercises/overhead_press.webp",
    description: "The standing barbell overhead press is the primary compound shoulder exercise, building deltoid mass and overhead pressing strength while challenging core stability.",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Trapezius", "Core"],
    instructions: [
      "Stand with feet shoulder-width apart. Hold the bar at shoulder height with an overhand grip, elbows slightly in front of the bar.",
      "Take a deep breath and brace your core and glutes to create a rigid torso.",
      "Press the bar straight up, moving your head back slightly to let the bar pass, then forward again.",
      "Lock out your elbows at the top with the bar directly over your mid-foot.",
      "Lower the bar back to shoulder height under control.",
    ],
    tips: "Squeeze your glutes and brace your abs hard to prevent lower-back hyperextension. Keep the bar path as vertical as possible. Flaring the elbows slightly forward (not fully out) is natural for most people.",
  },
  "Bicep Curls": {
    name: "Bicep Curls",
    category: "Arms",
    image: "/exercises/bicep_curl.webp",
    description: "The standing dumbbell curl is the classic bicep isolation exercise, building peak and overall arm size through a full range of supinated elbow flexion.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    instructions: [
      "Stand holding dumbbells at your sides with palms facing forward (supinated grip).",
      "Keep your upper arms stationary against your torso throughout the movement.",
      "Curl the dumbbells up toward your shoulders by flexing at the elbow.",
      "Squeeze the biceps hard at the top of the movement.",
      "Lower the dumbbells slowly back to the starting position, fully extending the elbow.",
    ],
    tips: "Avoid swinging your torso to lift the weight — this transfers the load away from the biceps. Slow down the lowering phase (eccentric) for greater muscle stimulus. Supinate your wrists fully at the top for maximum bicep contraction.",
  },
  "Tricep Dips": {
    name: "Tricep Dips",
    category: "Arms",
    image: "/exercises/tricep_dip.png",
    description: "Parallel bar dips are a compound upper-body exercise that heavily loads the triceps while also engaging the chest and anterior deltoids.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectorals", "Anterior Deltoids"],
    instructions: [
      "Grip the parallel bars and push yourself up to a straight-arm support position.",
      "Lean your torso slightly forward to shift emphasis toward the triceps.",
      "Lower your body by bending your elbows, keeping them close to your sides.",
      "Descend until your upper arms are roughly parallel to the floor.",
      "Press back up to the starting position by extending your elbows fully.",
    ],
    tips: "Keeping your torso more upright and elbows tucked close to your sides maximises tricep activation. Leaning forward too much shifts the load to the chest. Add weight with a dip belt once bodyweight becomes easy.",
  },
  "Lat Pulldowns": {
    name: "Lat Pulldowns",
    category: "Back",
    image: "/exercises/lat_pulldown.webp",
    description: "The lat pulldown is a cable-based vertical pulling exercise that builds lat width and is an excellent progression tool toward unassisted pull-ups.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Teres Major"],
    instructions: [
      "Sit at the lat pulldown machine and secure your thighs under the pads. Grip the bar wider than shoulder-width.",
      "Lean back slightly (about 10–15°) and depress your shoulder blades.",
      "Pull the bar down toward your upper chest by driving your elbows down and back.",
      "Squeeze your lats at the bottom of the movement.",
      "Allow the bar to rise slowly back to the starting position with arms fully extended.",
    ],
    tips: "Think about pulling your elbows to your hip pockets rather than pulling the bar down. Avoid using momentum or excessive body sway. A full stretch at the top of each rep maximises the range of motion.",
  },
  "Leg Press": {
    name: "Leg Press",
    category: "Legs",
    image: "/exercises/leg_press.webp",
    description: "The leg press machine allows heavy quad-dominant loading with reduced spinal stress, making it an excellent complement to free-weight squatting.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    instructions: [
      "Sit in the leg press machine with your back flat against the pad. Place feet shoulder-width apart on the footplate.",
      "Release the safety handles and lower the platform by bending your knees toward your chest.",
      "Descend until your knees are at roughly 90° or slightly below, keeping your lower back flat.",
      "Press the platform away by extending your knees and hips simultaneously.",
      "Lock out your legs at the top but avoid hyperextending the knees.",
    ],
    tips: "Never allow your lower back to round off the pad — this puts dangerous stress on the lumbar spine. Higher foot placement emphasises glutes and hamstrings; lower placement emphasises quads. Don't lock out aggressively.",
  },
  "Romanian Deadlifts": {
    name: "Romanian Deadlifts",
    category: "Legs",
    image: "/exercises/romanian_deadlift.webp",
    description: "The Romanian deadlift is a hip-hinge movement that targets the hamstrings and glutes through a long range of motion, building posterior chain strength and flexibility.",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Spinal Erectors", "Adductors"],
    instructions: [
      "Stand holding a barbell at hip height with an overhand grip, feet hip-width apart.",
      "Push your hips back while maintaining a flat back, lowering the bar along your legs.",
      "Feel a deep stretch in your hamstrings — typically the bar reaches mid-shin level.",
      "Drive your hips forward to return to the starting position, squeezing your glutes at the top.",
      "Keep the bar close to your body throughout the entire movement.",
    ],
    tips: "The movement is initiated by pushing your hips backward, not by bending your knees. Maintain a slight bend in the knees throughout. If you feel it more in your lower back than your hamstrings, you're likely rounding your spine.",
  },
  "Incline Bench Press": {
    name: "Incline Bench Press",
    category: "Chest",
    image: "/exercises/incline_bench_press.webp",
    description: "The incline barbell bench press targets the upper portion of the pectorals and anterior deltoids, building a fuller, more developed upper chest.",
    primaryMuscles: ["Upper Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Set the bench to a 30–45° incline. Lie back and grip the bar slightly wider than shoulder-width.",
      "Unrack the bar and hold it above your upper chest with arms extended.",
      "Lower the bar to your upper chest (below your clavicle) in a controlled arc.",
      "Press the bar back up to the starting position, exhaling as you push.",
      "Keep your feet flat on the floor and shoulder blades retracted throughout.",
    ],
    tips: "A 30° incline hits the upper chest more effectively than a steeper angle, which starts to shift the load to the shoulders. Keep the bar path slightly back toward the rack at the top to maintain shoulder safety.",
  },
  "Dumbbell Rows": {
    name: "Dumbbell Rows",
    category: "Back",
    image: "/exercises/dumbbell_row.webp",
    description: "The single-arm dumbbell row allows a greater range of motion than barbell rows and helps correct left-right strength imbalances in the back.",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Teres Major"],
    instructions: [
      "Place one knee and the same-side hand on a flat bench for support. Hold a dumbbell in the other hand.",
      "Let the dumbbell hang straight down with your arm fully extended and back flat.",
      "Pull the dumbbell up toward your hip, driving your elbow back and up.",
      "Squeeze your lat and rhomboid at the top of the movement.",
      "Lower the dumbbell slowly back to the starting position.",
    ],
    tips: "Think about pulling your elbow to the ceiling rather than pulling the dumbbell up. Allow a slight rotation of the torso at the top to get a full contraction. Keep your lower back neutral throughout.",
  },
  "Shoulder Press": {
    name: "Shoulder Press",
    category: "Shoulders",
    image: "/exercises/shoulder_press.png",
    description: "The seated dumbbell shoulder press builds deltoid mass and overhead strength while allowing a more natural wrist and elbow path compared to the barbell version.",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Trapezius"],
    instructions: [
      "Sit on an upright bench with back support. Hold dumbbells at shoulder height, palms facing forward.",
      "Press the dumbbells overhead in an arc, bringing them together at the top.",
      "Lock out your elbows at the top without letting the dumbbells touch.",
      "Lower the dumbbells back to shoulder height in a controlled manner.",
      "Keep your core braced and avoid arching your lower back excessively.",
    ],
    tips: "Avoid pressing straight up and then letting the dumbbells drift forward — keep them in line with your ears throughout. Using a slight neutral grip (palms facing each other) can reduce shoulder impingement risk.",
  },
  "Lunges": {
    name: "Lunges",
    category: "Legs",
    image: "/exercises/lunges.webp",
    description: "Dumbbell lunges are a unilateral leg exercise that builds quad and glute strength while improving balance, coordination, and hip flexibility.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Hip Flexors"],
    instructions: [
      "Stand holding dumbbells at your sides, feet together.",
      "Step forward with one foot, landing with your heel first.",
      "Lower your back knee toward the floor, keeping your front shin vertical.",
      "Your front thigh should be parallel to the floor at the bottom.",
      "Push through your front heel to return to the starting position, then alternate legs.",
    ],
    tips: "Keep your torso upright throughout — avoid leaning forward. The front knee should track over your second toe, not cave inward. Start with bodyweight to master the movement pattern before adding load.",
  },
  "Leg Curls": {
    name: "Leg Curls",
    category: "Legs",
    image: "/exercises/leg_curl.webp",
    description: "The lying leg curl is the primary hamstring isolation exercise, targeting the biceps femoris, semitendinosus, and semimembranosus through knee flexion.",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Gastrocnemius"],
    instructions: [
      "Lie face down on the leg curl machine with the padded roller just above your heels.",
      "Grip the handles for stability and keep your hips pressed into the pad.",
      "Curl your legs up toward your glutes by flexing at the knee.",
      "Squeeze your hamstrings hard at the top of the movement.",
      "Lower your legs slowly back to the starting position — don't let the weight drop.",
    ],
    tips: "Plantarflexing your feet (pointing toes) at the top of the movement increases hamstring activation. Avoid lifting your hips off the pad, as this reduces the range of motion and shifts load away from the hamstrings.",
  },
  "Leg Extensions": {
    name: "Leg Extensions",
    category: "Legs",
    image: "/exercises/leg_extension.webp",
    description: "The leg extension is a quad isolation exercise performed on a machine, targeting the rectus femoris and vastus muscles through knee extension.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    instructions: [
      "Sit on the leg extension machine with your back against the pad and knees at the edge of the seat.",
      "Position the padded roller just above your ankles.",
      "Extend your legs by straightening your knees until your legs are parallel to the floor.",
      "Squeeze your quads hard at the top of the movement.",
      "Lower the weight slowly back to the starting position.",
    ],
    tips: "Avoid using excessive weight that causes your hips to lift off the seat. Slow, controlled reps with a peak contraction at the top are more effective than heavy, momentum-driven reps. Some people find a slight toe-in or toe-out position more comfortable.",
  },
  "Calf Raises": {
    name: "Calf Raises",
    category: "Legs",
    image: "/exercises/calf_raise.webp",
    description: "Standing calf raises target the gastrocnemius through plantar flexion, building calf size and lower-leg strength.",
    primaryMuscles: ["Gastrocnemius"],
    secondaryMuscles: ["Soleus"],
    instructions: [
      "Stand on the edge of a step or calf raise platform with the balls of your feet on the edge.",
      "Let your heels drop below the step level for a full stretch.",
      "Rise up onto the balls of your feet as high as possible.",
      "Hold the peak contraction for a moment before lowering.",
      "Lower your heels back below the step level for a full stretch on each rep.",
    ],
    tips: "The calves respond well to high reps and a full range of motion. Pause at the bottom for a true stretch and at the top for a full contraction. Avoid bouncing through the movement — control every rep.",
  },
  "Chest Flyes": {
    name: "Chest Flyes",
    category: "Chest",
    image: "/exercises/chest_fly.webp",
    description: "Dumbbell chest flyes isolate the pectorals through a wide arc of shoulder horizontal adduction, providing a deep stretch and strong peak contraction.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Lie flat on a bench holding dumbbells above your chest, palms facing each other, elbows slightly bent.",
      "Lower the dumbbells in a wide arc out to your sides, maintaining the slight elbow bend.",
      "Feel a deep stretch across your chest at the bottom of the movement.",
      "Bring the dumbbells back together in the same arc, squeezing your chest at the top.",
      "Do not straighten your elbows — keep them slightly bent throughout.",
    ],
    tips: "Think about hugging a large tree — the movement is a wide arc, not a press. Keep the elbows at a fixed angle throughout. Go lighter than you think you need to; this is an isolation exercise, not a strength movement.",
  },
  "Lateral Raises": {
    name: "Lateral Raises",
    category: "Shoulders",
    image: "/exercises/lateral_raise.webp",
    description: "Dumbbell lateral raises isolate the lateral deltoid head, which is primarily responsible for shoulder width and the coveted 'capped' shoulder look.",
    primaryMuscles: ["Lateral Deltoids"],
    secondaryMuscles: ["Anterior Deltoids", "Upper Trapezius"],
    instructions: [
      "Stand holding dumbbells at your sides with a slight bend in your elbows.",
      "Raise both arms out to the sides simultaneously, leading with your elbows.",
      "Lift until your arms are parallel to the floor (shoulder height).",
      "Hold briefly at the top, then lower the dumbbells slowly back to your sides.",
      "Avoid shrugging your shoulders or using momentum.",
    ],
    tips: "Tilt the dumbbells slightly so the front is a little lower than the back (like pouring a jug) — this internally rotates the shoulder and maximises lateral delt activation. Use light weight and focus on the muscle contraction over load.",
  },
  "Front Raises": {
    name: "Front Raises",
    category: "Shoulders",
    image: "/exercises/front_raise.webp",
    description: "Dumbbell front raises isolate the anterior deltoid head through shoulder flexion, complementing pressing movements for complete front delt development.",
    primaryMuscles: ["Anterior Deltoids"],
    secondaryMuscles: ["Lateral Deltoids", "Upper Pectorals"],
    instructions: [
      "Stand holding dumbbells in front of your thighs, palms facing your body.",
      "Raise both arms forward and upward with a slight bend in the elbows.",
      "Lift until your arms are parallel to the floor or slightly above.",
      "Hold briefly at the top, then lower the dumbbells slowly back to the starting position.",
      "Keep your torso still — avoid swinging to generate momentum.",
    ],
    tips: "The anterior deltoid is already heavily worked in pressing movements, so front raises are best used as a finishing exercise with moderate weight. Alternate arms to increase time under tension and control.",
  },
  "Hammer Curls": {
    name: "Hammer Curls",
    category: "Arms",
    image: "/exercises/hammer_curl.webp",
    description: "Hammer curls use a neutral (thumbs-up) grip to emphasise the brachialis and brachioradialis alongside the biceps, building arm thickness and forearm strength.",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps Brachii"],
    instructions: [
      "Stand holding dumbbells at your sides with a neutral grip (palms facing your body).",
      "Keep your upper arms stationary and curl both dumbbells up simultaneously.",
      "Lift until your thumbs are near your shoulders.",
      "Squeeze at the top, then lower slowly back to the starting position.",
      "Maintain the neutral grip throughout — do not rotate your wrists.",
    ],
    tips: "The brachialis lies underneath the biceps and when developed pushes the biceps up, creating a larger arm appearance. Hammer curls are one of the best exercises to target it. Alternate arms to focus on each side.",
  },
  "Tricep Extensions": {
    name: "Tricep Extensions",
    category: "Arms",
    image: "/exercises/tricep_extension.webp",
    description: "The overhead dumbbell tricep extension targets the long head of the triceps — the largest portion — through a full overhead range of motion.",
    primaryMuscles: ["Triceps Brachii (long head)"],
    secondaryMuscles: ["Triceps Brachii (lateral & medial heads)"],
    instructions: [
      "Sit on a bench and hold a single dumbbell with both hands, palms cupping the top plate.",
      "Press the dumbbell overhead until your arms are fully extended.",
      "Lower the dumbbell behind your head by bending your elbows, keeping them pointing straight up.",
      "Descend until you feel a full stretch in your triceps.",
      "Extend your elbows to press the dumbbell back to the starting position.",
    ],
    tips: "The overhead position stretches the long head of the triceps maximally, making this one of the most effective tricep exercises for mass. Keep your elbows close together and pointing straight up — don't let them flare out.",
  },
  "Face Pulls": {
    name: "Face Pulls",
    category: "Shoulders",
    image: "/exercises/face_pull.webp",
    description: "Face pulls target the rear deltoids and external rotators of the shoulder, improving posture, shoulder health, and posterior delt development.",
    primaryMuscles: ["Rear Deltoids"],
    secondaryMuscles: ["External Rotators", "Mid Trapezius", "Rhomboids"],
    instructions: [
      "Set a cable machine to upper-chest height and attach a rope. Grip the rope with both hands, thumbs facing you.",
      "Step back until there is tension in the cable. Stand with feet shoulder-width apart.",
      "Pull the rope toward your face, separating your hands and flaring your elbows out to the sides.",
      "Aim to pull your hands to either side of your face with elbows at shoulder height.",
      "Hold briefly at the peak contraction, then return slowly to the starting position.",
    ],
    tips: "Face pulls are one of the best exercises for shoulder health and posture correction. Focus on the external rotation component — pulling your hands apart at the end of the movement. Use a weight that allows full range of motion.",
  },
  "Cable Rows": {
    name: "Cable Rows",
    category: "Back",
    image: "/exercises/cable_row.webp",
    description: "The seated cable row provides constant tension throughout the range of motion, building mid-back thickness and improving posture through horizontal pulling.",
    primaryMuscles: ["Mid Trapezius", "Rhomboids", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    instructions: [
      "Sit at the cable row machine with feet on the footrests and knees slightly bent.",
      "Grip the handle with both hands, arms extended, and sit up tall with a flat back.",
      "Pull the handle toward your lower abdomen by driving your elbows back.",
      "Squeeze your shoulder blades together at the end of the pull.",
      "Extend your arms slowly back to the starting position, allowing a slight forward lean for a full stretch.",
    ],
    tips: "Avoid rounding your lower back or using excessive body sway. The slight forward lean at the start of each rep (not a full hinge) allows a greater range of motion and better lat stretch. Keep your chest up throughout.",
  },
  "Preacher Curls": {
    name: "Preacher Curls",
    category: "Arms",
    image: "/exercises/preacher_curl.webp",
    description: "The preacher curl isolates the biceps by eliminating shoulder flexion cheating, providing a unique stretch at the bottom and peak contraction at the top.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis"],
    instructions: [
      "Sit at the preacher curl bench and place your upper arms flat on the angled pad.",
      "Grip the barbell or EZ-bar with an underhand grip at the bottom of the movement.",
      "Curl the bar upward by flexing your elbows, keeping your upper arms on the pad.",
      "Squeeze your biceps hard at the top.",
      "Lower the bar slowly back to the fully extended position — don't let it drop.",
    ],
    tips: "The bottom position (full extension) is where the biceps are most stretched and most vulnerable. Control the lowering phase carefully. Avoid locking out aggressively at the bottom as this can stress the elbow joint.",
  },
  "Skull Crushers": {
    name: "Skull Crushers",
    category: "Arms",
    image: "/exercises/skull_crusher.png",
    description: "Skull crushers (lying tricep extensions) are a compound tricep exercise that loads all three heads of the triceps through elbow extension.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Lie flat on a bench and hold a barbell or EZ-bar with arms extended straight up above your chest.",
      "Keep your upper arms perpendicular to the floor and stationary throughout.",
      "Lower the bar toward your forehead by bending your elbows.",
      "Stop just before the bar reaches your forehead, then extend your elbows to press back up.",
      "Keep the movement slow and controlled, especially on the lowering phase.",
    ],
    tips: "Despite the name, the bar should travel toward your forehead, not your skull. Some lifters find lowering slightly behind the head (to the forehead/top of head) provides a better stretch. Use an EZ-bar to reduce wrist strain.",
  },
  "Hip Thrusts": {
    name: "Hip Thrusts",
    category: "Legs",
    image: "/exercises/hip_thrust.webp",
    description: "The barbell hip thrust is the most effective glute isolation exercise, providing peak glute activation at the top of the movement through hip extension.",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    instructions: [
      "Sit on the floor with your upper back against a bench and a barbell across your hips.",
      "Plant your feet flat on the floor, hip-width apart, toes slightly out.",
      "Drive through your heels to thrust your hips upward, squeezing your glutes hard.",
      "At the top, your torso should be parallel to the floor and shins vertical.",
      "Lower your hips back to the floor under control and repeat.",
    ],
    tips: "The key to maximising glute activation is a full hip extension at the top with a strong glute squeeze. Use a barbell pad for comfort. Avoid hyperextending your lower back — the movement comes from the hips, not the spine.",
  },
  "Planks": {
    name: "Planks",
    category: "Core",
    image: "/exercises/plank.webp",
    description: "The forearm plank is a fundamental core stability exercise that builds isometric strength in the abs, obliques, and spinal stabilisers.",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Obliques", "Spinal Erectors", "Glutes", "Shoulders"],
    instructions: [
      "Start in a push-up position, then lower onto your forearms with elbows directly under your shoulders.",
      "Form a straight line from your head to your heels — no sagging hips or raised buttocks.",
      "Brace your core as if bracing for a punch, and squeeze your glutes.",
      "Keep your neck neutral — look at the floor just in front of your hands.",
      "Hold the position for the desired duration, breathing steadily.",
    ],
    tips: "Quality beats quantity — a 30-second plank with perfect form is more beneficial than a 2-minute plank with a sagging back. Focus on creating full-body tension: squeeze your fists, glutes, and abs simultaneously.",
  },
  "Russian Twists": {
    name: "Russian Twists",
    category: "Core",
    image: "/exercises/russian_twist.webp",
    description: "Russian twists are a rotational core exercise that targets the obliques and builds rotational strength and stability.",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Rectus Abdominis", "Hip Flexors"],
    instructions: [
      "Sit on the floor with knees bent and feet slightly raised or flat on the floor.",
      "Lean your torso back to approximately 45°, keeping your back straight.",
      "Hold a weight plate, dumbbell, or medicine ball with both hands in front of your chest.",
      "Rotate your torso to one side, bringing the weight toward the floor beside your hip.",
      "Rotate to the other side in a controlled manner, completing one full rep.",
    ],
    tips: "The rotation should come from your torso, not just your arms. Keep your chest up and avoid rounding your lower back. Elevating your feet increases the difficulty by removing a base of support. Move slowly and deliberately.",
  },
  // Additional exercises with images from the library
  "Incline Press": {
    name: "Incline Press",
    category: "Chest",
    image: "/exercises/incline_press.png",
    description: "The incline dumbbell press targets the upper chest and anterior deltoids, building a fuller upper pectoral region.",
    primaryMuscles: ["Upper Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Set a bench to 30–45°. Sit back holding dumbbells at shoulder height, palms forward.",
      "Press the dumbbells upward and slightly inward until arms are extended.",
      "Lower the dumbbells back to chest level in a controlled arc.",
      "Keep your shoulder blades retracted and back against the bench.",
    ],
    tips: "A 30° angle is optimal for upper chest activation without shifting too much load to the shoulders. Keep the dumbbells in line with your upper chest throughout.",
  },
  "Dumbbell Press": {
    name: "Dumbbell Press",
    category: "Chest",
    image: "/exercises/dumbbell_press.webp",
    description: "The flat dumbbell press allows a greater range of motion than the barbell bench press and helps correct strength imbalances between sides.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie flat on a bench holding dumbbells at chest height, palms facing forward.",
      "Press the dumbbells upward until arms are fully extended.",
      "Lower the dumbbells to chest level in a controlled arc.",
      "Keep your feet flat on the floor and back slightly arched.",
    ],
    tips: "Allow the dumbbells to travel slightly wider than the barbell path for a better chest stretch. Squeeze the dumbbells together at the top to maximise pectoral contraction.",
  },
  "Dumbbell Fly": {
    name: "Dumbbell Fly",
    category: "Chest",
    image: "/exercises/dumbbell_fly.webp",
    description: "The dumbbell fly isolates the pectorals through a wide arc of shoulder horizontal adduction, providing a deep stretch.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Lie flat on a bench with dumbbells above your chest, palms facing each other.",
      "Lower the dumbbells in a wide arc with a slight elbow bend.",
      "Feel a deep chest stretch at the bottom.",
      "Bring the dumbbells back together in the same arc.",
    ],
    tips: "Keep a fixed elbow angle throughout. This is an isolation exercise — use moderate weight and focus on the stretch and squeeze.",
  },
  "Cable Fly (High-to-Low)": {
    name: "Cable Fly (High-to-Low)",
    category: "Chest",
    image: "/exercises/cable_fly.webp",
    description: "The high-to-low cable fly targets the lower pectorals with constant cable tension throughout the movement.",
    primaryMuscles: ["Lower Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Set cables to the highest position. Stand in the middle and grip one handle in each hand.",
      "Step forward slightly and lean forward from the hips.",
      "Bring your hands together in a downward arc in front of your lower abdomen.",
      "Squeeze your chest at the bottom, then return slowly.",
    ],
    tips: "The cable provides constant tension unlike dumbbells. Focus on the squeeze at the bottom of each rep.",
  },
  "Skullcrushers": {
    name: "Skullcrushers",
    category: "Arms",
    image: "/exercises/skullcrusher.png",
    description: "Skullcrushers are a lying tricep extension that loads all three heads of the triceps through elbow extension.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Lie on a bench with an EZ-bar or barbell held above your chest, arms extended.",
      "Lower the bar toward your forehead by bending only at the elbows.",
      "Extend your elbows to press back to the starting position.",
    ],
    tips: "Keep your upper arms perpendicular to the floor. Use an EZ-bar to reduce wrist strain.",
  },
  "Rope Pushdowns": {
    name: "Rope Pushdowns",
    category: "Arms",
    image: "/exercises/rope_pushdown.webp",
    description: "Cable rope pushdowns isolate the triceps with constant tension, and the rope allows a wider range of motion at the bottom.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Attach a rope to a high cable pulley. Stand facing the machine and grip the rope with both hands.",
      "Keep your upper arms against your sides and push the rope down.",
      "At the bottom, spread the rope ends apart to maximise the contraction.",
      "Return slowly to the starting position.",
    ],
    tips: "Flaring the rope ends outward at the bottom increases lateral head activation. Keep your elbows tucked in throughout.",
  },
  "Bulgarian Split Squats": {
    name: "Bulgarian Split Squats",
    category: "Legs",
    image: "/exercises/bulgarian_split_squat.webp",
    description: "The Bulgarian split squat is a demanding unilateral leg exercise that builds quad and glute strength while improving hip mobility.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    instructions: [
      "Stand in front of a bench and place your rear foot on it, laces down.",
      "Step your front foot forward far enough that your shin stays vertical when you descend.",
      "Lower your back knee toward the floor, keeping your torso upright.",
      "Drive through your front heel to return to the starting position.",
    ],
    tips: "This exercise is notoriously difficult. Start with bodyweight to master the balance before adding load. A longer front foot position emphasises the glutes; shorter emphasises the quads.",
  },
  "Hanging Leg Raises": {
    name: "Hanging Leg Raises",
    category: "Core",
    image: "/exercises/hanging_leg_raise.webp",
    description: "Hanging leg raises build lower abdominal strength and hip flexor endurance through a full range of hip flexion while hanging from a bar.",
    primaryMuscles: ["Lower Rectus Abdominis", "Hip Flexors"],
    secondaryMuscles: ["Obliques", "Grip Strength"],
    instructions: [
      "Hang from a pull-up bar with an overhand grip, arms fully extended.",
      "Brace your core and raise your legs by flexing your hips and knees.",
      "Lift until your thighs are at least parallel to the floor, or higher for more difficulty.",
      "Lower your legs slowly back to the starting position.",
    ],
    tips: "Avoid swinging — control the movement throughout. For more difficulty, keep your legs straight. Focus on posterior pelvic tilt at the top to maximise lower ab activation.",
  },
  "Ab Wheel": {
    name: "Ab Wheel",
    category: "Core",
    image: "/exercises/ab_wheel.webp",
    description: "The ab wheel rollout is one of the most demanding core exercises, building anti-extension core strength through a long lever arm.",
    primaryMuscles: ["Rectus Abdominis", "Transverse Abdominis"],
    secondaryMuscles: ["Obliques", "Lats", "Shoulders"],
    instructions: [
      "Kneel on the floor and grip the ab wheel handles with both hands.",
      "Start with the wheel directly under your shoulders.",
      "Roll the wheel forward, extending your body as far as you can while keeping your back flat.",
      "Contract your core to pull the wheel back to the starting position.",
    ],
    tips: "Start with partial rollouts if you cannot complete a full rollout with a neutral spine. Never let your lower back sag — this is a core stability exercise, not a hip flexor exercise.",
  },
  "Arnold Press": {
    name: "Arnold Press",
    category: "Shoulders",
    image: "/exercises/arnold_press.webp",
    description: "The Arnold Press is a dumbbell shoulder press variation that rotates through a full range of motion, hitting all three heads of the deltoid.",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Posterior Deltoids", "Triceps", "Upper Traps"],
    instructions: [
      "Sit on a bench with back support, holding dumbbells at shoulder height with palms facing you.",
      "Press the dumbbells up while rotating your wrists outward so palms face forward at the top.",
      "Fully extend your arms overhead without locking out the elbows.",
      "Reverse the motion — rotate palms back inward as you lower to the start.",
    ],
    tips: "Keep the movement smooth and controlled. Don't rush the rotation — the full range of motion is what makes this exercise effective for all three delt heads.",
  },
  "Back Extensions": {
    name: "Back Extensions",
    category: "Back",
    image: "/exercises/back_extension.webp",
    description: "Back extensions on a hyperextension bench strengthen the spinal erectors, glutes, and hamstrings through a controlled hip hinge movement.",
    primaryMuscles: ["Spinal Erectors"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    instructions: [
      "Position yourself on the hyperextension bench with your hips on the pad and feet secured.",
      "Cross your arms over your chest or place hands behind your head.",
      "Lower your torso toward the floor in a controlled arc.",
      "Extend back up until your body forms a straight line — do not hyperextend.",
    ],
    tips: "Squeeze your glutes at the top of each rep. Avoid rounding your lower back at the bottom. For added resistance, hold a weight plate against your chest.",
  },
  "Battle Ropes": {
    name: "Battle Ropes",
    category: "Cardio",
    image: "/exercises/battle_ropes.webp",
    description: "Battle ropes are a high-intensity conditioning tool that builds cardiovascular fitness, upper-body endurance, and core stability simultaneously.",
    primaryMuscles: ["Cardiovascular System", "Shoulders"],
    secondaryMuscles: ["Core", "Arms", "Back"],
    instructions: [
      "Stand in an athletic stance with knees slightly bent, holding one rope end in each hand.",
      "Alternate raising and lowering each arm rapidly to create wave patterns in the ropes.",
      "Keep your core braced and back straight throughout.",
      "Work in intervals (e.g., 20–40 seconds on, 20 seconds rest).",
    ],
    tips: "Vary the wave patterns — alternating waves, simultaneous waves, and slams all target different aspects of conditioning. Stay low in your stance to protect your lower back.",
  },
  "Box Jumps": {
    name: "Box Jumps",
    category: "Cardio",
    image: "/exercises/box_jump.webp",
    description: "Box jumps are a plyometric exercise that develops explosive lower-body power, coordination, and cardiovascular conditioning.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    instructions: [
      "Stand facing the box at a comfortable distance, feet shoulder-width apart.",
      "Swing your arms back and bend your knees to load the jump.",
      "Explode upward, swinging your arms forward, and land softly on top of the box with both feet.",
      "Stand fully upright on the box, then step down carefully.",
    ],
    tips: "Land softly with knees bent to absorb impact. Step down rather than jumping down to reduce joint stress. Start with a lower box and progress height gradually.",
  },
  "Burpees": {
    name: "Burpees",
    category: "Cardio",
    image: "/exercises/burpee.webp",
    description: "Burpees are a full-body calisthenics exercise combining a squat, plank, push-up, and jump for maximum cardiovascular and muscular conditioning.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Chest", "Shoulders", "Quadriceps", "Core"],
    instructions: [
      "Stand with feet shoulder-width apart, then squat down and place hands on the floor.",
      "Jump or step your feet back into a high plank position.",
      "Perform a push-up (optional for added difficulty).",
      "Jump your feet back to your hands, then explode upward into a jump with arms overhead.",
    ],
    tips: "Scale the intensity by stepping instead of jumping, or removing the push-up. Focus on maintaining a neutral spine in the plank position. Use burpees in HIIT intervals for maximum conditioning benefit.",
  },
  "Cable Crunches": {
    name: "Cable Crunches",
    category: "Core",
    image: "/exercises/cable_crunch.webp",
    description: "Cable crunches provide constant tension throughout the range of motion, making them one of the most effective weighted abdominal exercises.",
    primaryMuscles: ["Rectus Abdominis"],
    secondaryMuscles: ["Obliques"],
    instructions: [
      "Kneel in front of a cable machine with a rope attachment set at the top.",
      "Hold the rope behind your head with elbows pointing down.",
      "Crunch your torso downward toward your knees, rounding your upper back.",
      "Hold the contracted position briefly, then slowly return to the start.",
    ],
    tips: "The movement should come from your abs, not your hip flexors. Keep your hips stationary — only your upper body should move. Focus on the contraction at the bottom of each rep.",
  },
  "Cable Curls": {
    name: "Cable Curls",
    category: "Arms",
    image: "/exercises/cable_curl.webp",
    description: "Cable curls provide constant tension on the biceps throughout the entire range of motion, unlike free weights which have a strength curve.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    instructions: [
      "Stand facing a low cable pulley with a straight bar or EZ-bar attachment.",
      "Grip the bar with an underhand (supinated) grip, hands shoulder-width apart.",
      "Curl the bar upward toward your shoulders, keeping elbows pinned to your sides.",
      "Squeeze the biceps at the top, then lower slowly back to the start.",
    ],
    tips: "The cable provides resistance at the bottom of the movement where dumbbells are weakest. Keep your elbows stationary — don't let them drift forward. Control the eccentric (lowering) phase.",
  },
  "Cable Fly (High-to-Low)": {
    name: "Cable Fly (High-to-Low)",
    category: "Chest",
    image: "/exercises/cable_fly_high_to_low.webp",
    description: "High-to-low cable flyes target the lower pectoral fibres through a sweeping arc motion with constant cable tension.",
    primaryMuscles: ["Pectorals (lower)"],
    secondaryMuscles: ["Anterior Deltoids", "Biceps"],
    instructions: [
      "Set both cable pulleys to the highest position. Stand in the centre with a handle in each hand.",
      "Step forward slightly and lean forward from the hips for stability.",
      "With a slight bend in the elbows, sweep your arms downward and inward in an arc toward your hips.",
      "Squeeze your chest at the bottom, then slowly return to the start.",
    ],
    tips: "Think of hugging a large tree — keep the arc shape throughout. Don't let your elbows bend further as you pull. The constant tension from the cables makes this superior to dumbbell flyes for lower chest.",
  },
  "Cable Fly (Low-to-High)": {
    name: "Cable Fly (Low-to-High)",
    category: "Chest",
    image: "/exercises/cable_fly_low_to_high.webp",
    description: "Low-to-high cable flyes target the upper pectoral fibres through an upward sweeping arc with constant cable tension.",
    primaryMuscles: ["Pectorals (upper)"],
    secondaryMuscles: ["Anterior Deltoids", "Biceps"],
    instructions: [
      "Set both cable pulleys to the lowest position. Stand in the centre with a handle in each hand.",
      "Step forward slightly and lean forward from the hips for stability.",
      "With a slight bend in the elbows, sweep your arms upward and inward in an arc toward chest height.",
      "Squeeze your chest at the top, then slowly return to the start.",
    ],
    tips: "Focus on the upper chest contraction at the top of the movement. Keep your core braced to prevent your lower back from arching. This is excellent for building upper chest fullness.",
  },
  "Cable Kickbacks": {
    name: "Cable Kickbacks",
    category: "Arms",
    image: "/exercises/cable_kickback.webp",
    description: "Cable kickbacks isolate the triceps through elbow extension with constant cable tension, particularly effective for the long head.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: [],
    instructions: [
      "Attach an ankle strap to a low cable pulley and secure it to your ankle.",
      "Or use a D-handle, hinge forward at the hips with one hand on a support.",
      "Keep your upper arm parallel to the floor and extend your forearm backward.",
      "Fully extend the elbow, squeeze the tricep, then return slowly.",
    ],
    tips: "Keep your upper arm completely stationary — only the forearm should move. Squeeze hard at full extension. The cable provides constant tension unlike dumbbell kickbacks which lose tension at the bottom.",
  },
  "Cable Lateral Raises": {
    name: "Cable Lateral Raises",
    category: "Shoulders",
    image: "/exercises/cable_lateral_raise.webp",
    description: "Cable lateral raises provide constant tension on the lateral deltoid throughout the full range of motion, unlike dumbbells which lose tension at the bottom.",
    primaryMuscles: ["Lateral Deltoids"],
    secondaryMuscles: ["Anterior Deltoids", "Traps"],
    instructions: [
      "Stand sideways to a low cable pulley, holding a D-handle with the hand furthest from the machine.",
      "Keep a slight bend in the elbow and raise your arm out to the side to shoulder height.",
      "Pause briefly at the top, then lower slowly back to the start.",
      "Complete all reps on one side before switching.",
    ],
    tips: "Lead with your elbow, not your hand. Avoid shrugging — keep your traps relaxed. The cable provides resistance at the bottom of the movement where dumbbells are weakest.",
  },
  "Chest Dips": {
    name: "Chest Dips",
    category: "Chest",
    image: "/exercises/chest_dip.webp",
    description: "Chest dips are a bodyweight compound exercise that heavily loads the lower pectorals, anterior deltoids, and triceps through a deep range of motion.",
    primaryMuscles: ["Pectorals (lower)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Grip parallel bars and support your bodyweight with arms extended.",
      "Lean your torso forward slightly (15–30°) to shift emphasis to the chest.",
      "Lower your body by bending your elbows, allowing them to flare slightly outward.",
      "Descend until your upper arms are parallel to the floor or slightly below.",
      "Press back up to the starting position.",
    ],
    tips: "The forward lean is key — the more you lean, the more chest activation. Keep your elbows from flaring too wide to protect your shoulders. Add weight with a dip belt once bodyweight becomes easy.",
  },
  "Chest-Supported Row": {
    name: "Chest-Supported Row",
    category: "Back",
    image: "/exercises/chest_supported_row.webp",
    description: "The chest-supported row eliminates lower back involvement by bracing the chest against a bench, allowing full focus on the back muscles.",
    primaryMuscles: ["Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Latissimus Dorsi", "Rear Deltoids", "Biceps"],
    instructions: [
      "Set an incline bench to 30–45° and lie face down with your chest on the pad.",
      "Hold dumbbells with arms hanging straight down, palms facing each other.",
      "Row the dumbbells up toward your hips, driving your elbows back and squeezing your shoulder blades.",
      "Hold the top position briefly, then lower slowly.",
    ],
    tips: "Focus on squeezing your shoulder blades together at the top. Keep your chest in contact with the bench throughout — this eliminates cheating. Great for people with lower back issues.",
  },
  "Close-Grip Bench": {
    name: "Close-Grip Bench",
    category: "Arms",
    image: "/exercises/close_grip_bench.webp",
    description: "The close-grip bench press is a compound tricep exercise that also works the chest and shoulders, allowing heavy loading of the triceps.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectorals", "Anterior Deltoids"],
    instructions: [
      "Lie on a flat bench and grip the barbell with hands shoulder-width apart or slightly narrower.",
      "Unrack the bar and hold it above your lower chest with elbows tucked close to your sides.",
      "Lower the bar to your lower chest/upper abdomen, keeping elbows in.",
      "Press the bar back up explosively, fully extending the elbows.",
    ],
    tips: "Don't go too narrow — hands inside shoulder-width can strain the wrists. Keep elbows tucked at about 45° to your torso. This is one of the best mass-builders for the triceps.",
  },
  "Concentration Curls": {
    name: "Concentration Curls",
    category: "Arms",
    image: "/exercises/concentration_curl.webp",
    description: "Concentration curls isolate the biceps by bracing the elbow against the inner thigh, eliminating momentum and maximising the mind-muscle connection.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis"],
    instructions: [
      "Sit on a bench with legs spread, holding a dumbbell in one hand.",
      "Brace the back of your upper arm against the inner thigh of the same side.",
      "Curl the dumbbell upward toward your shoulder, fully supinating the wrist at the top.",
      "Lower slowly back to full extension.",
    ],
    tips: "The brace against your thigh prevents any shoulder involvement, making this a pure bicep isolation exercise. Supinate (rotate) your wrist at the top for maximum bicep contraction. Control the negative.",
  },
  "Cuban Rotations": {
    name: "Cuban Rotations",
    category: "Shoulders",
    image: "/exercises/cuban_rotation.webp",
    description: "Cuban rotations are a shoulder health and rotator cuff strengthening exercise that trains external rotation under load.",
    primaryMuscles: ["Rotator Cuff", "Posterior Deltoids"],
    secondaryMuscles: ["Lateral Deltoids", "Traps"],
    instructions: [
      "Stand holding dumbbells with arms at your sides.",
      "Raise your elbows to shoulder height with a 90° bend (like a goalpost position).",
      "Rotate your forearms upward so the dumbbells point toward the ceiling.",
      "Reverse the rotation back to the goalpost position, then lower arms to the start.",
    ],
    tips: "Use very light weight — this is a rotator cuff exercise, not a strength exercise. The movement should be smooth and controlled. Great as a warm-up before pressing movements.",
  },
  "Cycling": {
    name: "Cycling",
    category: "Cardio",
    image: "/exercises/cycling.webp",
    description: "Stationary cycling is a low-impact cardiovascular exercise that builds aerobic fitness and lower-body endurance with minimal joint stress.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    instructions: [
      "Adjust the seat height so your knee has a slight bend at the bottom of the pedal stroke.",
      "Start at a comfortable resistance and warm up for 5 minutes.",
      "Maintain a cadence of 70–90 RPM for steady-state cardio.",
      "Cool down with 5 minutes of easy pedalling.",
    ],
    tips: "Keep your upper body relaxed and avoid hunching over the handlebars. For HIIT, alternate 20–30 second sprints with 40–60 second recovery periods. Adjust resistance to match your training goal.",
  },
  "Decline Bench Press": {
    name: "Decline Bench Press",
    category: "Chest",
    image: "/exercises/decline_bench_press.webp",
    description: "The decline bench press targets the lower pectoral fibres through a pressing motion on a downward-angled bench.",
    primaryMuscles: ["Pectorals (lower)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Secure your feet under the leg pads on a decline bench set to 15–30°.",
      "Grip the barbell slightly wider than shoulder-width.",
      "Lower the bar to your lower chest in a controlled arc.",
      "Press the bar back up to the starting position, fully extending the arms.",
    ],
    tips: "The decline angle reduces shoulder strain compared to flat bench for some people. Lower the bar to your lower chest (not upper chest) to maximise lower pec activation. Keep your feet firmly secured.",
  },
  "Elliptical": {
    name: "Elliptical",
    category: "Cardio",
    image: "/exercises/elliptical.webp",
    description: "The elliptical machine provides a low-impact full-body cardio workout that mimics running without the joint stress.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Glutes", "Shoulders"],
    instructions: [
      "Step onto the pedals and grip the moving handles.",
      "Begin with a 5-minute warm-up at low resistance.",
      "Maintain an upright posture and push/pull the handles to engage your upper body.",
      "Adjust resistance and incline to vary intensity.",
    ],
    tips: "Don't lean heavily on the handles — this reduces the caloric burn. Try pedalling in reverse to shift emphasis to the hamstrings and glutes. Aim for 65–75% of max heart rate for steady-state cardio.",
  },
  "Frog Pumps": {
    name: "Frog Pumps",
    category: "Legs",
    image: "/exercises/frog_pump.webp",
    description: "Frog pumps are a glute isolation exercise performed lying on your back with feet together, providing a unique hip extension angle that maximises glute activation.",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    instructions: [
      "Lie on your back with the soles of your feet pressed together (butterfly/frog position).",
      "Place your feet close to your glutes.",
      "Drive your hips upward by squeezing your glutes, lifting your hips off the floor.",
      "Hold the top position for 1–2 seconds, then lower slowly.",
    ],
    tips: "The frog position externally rotates the hips, which pre-stretches the glutes and increases activation. Use high reps (15–30) for a great glute pump. Can be loaded with a barbell or weight plate on the hips.",
  },
  "Front Squats": {
    name: "Front Squats",
    category: "Legs",
    image: "/exercises/front_squat.webp",
    description: "The front squat places the barbell on the front of the shoulders, shifting emphasis to the quadriceps and requiring greater core and upper back strength.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core", "Upper Back"],
    instructions: [
      "Rest the barbell on your front deltoids with elbows high and parallel to the floor.",
      "Use a clean grip (fingers under bar) or cross-arm grip for stability.",
      "Squat down keeping your torso upright and elbows high throughout.",
      "Drive back up through your heels to the starting position.",
    ],
    tips: "Keeping elbows high is critical — if they drop, the bar will roll forward. Front squats require more ankle and thoracic mobility than back squats. Use wrist wraps if the clean grip is uncomfortable.",
  },
  "Good Mornings": {
    name: "Good Mornings",
    category: "Back",
    image: "/exercises/good_morning.webp",
    description: "Good mornings are a barbell hip hinge exercise that strengthens the spinal erectors, hamstrings, and glutes through a controlled forward lean.",
    primaryMuscles: ["Spinal Erectors", "Hamstrings"],
    secondaryMuscles: ["Glutes", "Core"],
    instructions: [
      "Place a barbell on your upper back as if setting up for a squat.",
      "Stand with feet shoulder-width apart and a slight bend in the knees.",
      "Hinge at the hips, pushing them backward while lowering your torso forward.",
      "Lower until your torso is roughly parallel to the floor, keeping your back flat.",
      "Drive your hips forward to return to the starting position.",
    ],
    tips: "Never round your lower back on this exercise. Start very light to learn the movement pattern. Think of it as a Romanian deadlift with the bar on your back. Keep the bar close to your centre of mass.",
  },
  "Guillotine Press": {
    name: "Guillotine Press",
    category: "Chest",
    image: "/exercises/guillotine_press.webp",
    description: "The guillotine press (neck press) lowers the bar to the neck/upper chest with wide elbows, maximising upper pectoral stretch and activation.",
    primaryMuscles: ["Pectorals (upper)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    instructions: [
      "Lie on a flat bench and grip the barbell with a wide grip.",
      "Unrack the bar and position it over your neck/upper chest.",
      "Lower the bar slowly to your upper chest/neck area with elbows flared wide.",
      "Press back up to the starting position.",
    ],
    tips: "Use lighter weight than your regular bench press — the wide elbow position reduces mechanical advantage. This exercise carries higher shoulder injury risk; use a spotter and avoid if you have shoulder issues.",
  },
  "HIIT Training": {
    name: "HIIT Training",
    category: "Cardio",
    image: "/exercises/hiit_training.webp",
    description: "High-Intensity Interval Training alternates between short bursts of maximum effort and recovery periods, maximising caloric burn and cardiovascular adaptation.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Full Body"],
    instructions: [
      "Warm up for 5 minutes at low intensity.",
      "Perform 20–40 seconds of maximum effort exercise (sprints, burpees, jump squats, etc.).",
      "Rest or perform low-intensity movement for 10–40 seconds.",
      "Repeat for 8–20 rounds depending on fitness level.",
      "Cool down for 5 minutes.",
    ],
    tips: "True HIIT requires maximum effort during work intervals — if you can hold a conversation, you're not working hard enough. Limit HIIT sessions to 2–3 per week to allow adequate recovery.",
  },
  "Hack Squat": {
    name: "Hack Squat",
    category: "Legs",
    image: "/exercises/hack_squat.webp",
    description: "The hack squat machine allows heavy quad loading in a guided movement pattern, reducing lower back stress compared to free barbell squats.",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    instructions: [
      "Step onto the hack squat machine and position your back against the padded backrest.",
      "Place feet shoulder-width apart on the platform, toes slightly out.",
      "Release the safety handles and lower your body by bending your knees.",
      "Descend until your thighs are at least parallel to the platform.",
      "Drive through your heels to return to the starting position.",
    ],
    tips: "Placing feet higher on the platform increases glute and hamstring involvement. Placing feet lower increases quad emphasis. Don't lock out your knees completely at the top to maintain tension.",
  },
  "Incline Dumbbell Curls": {
    name: "Incline Dumbbell Curls",
    category: "Arms",
    image: "/exercises/incline_dumbbell_curl.webp",
    description: "Incline dumbbell curls place the biceps in a stretched position at the bottom, maximising the long head of the bicep and creating a superior peak contraction.",
    primaryMuscles: ["Biceps Brachii (long head)"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    instructions: [
      "Set an incline bench to 45–60° and sit back with a dumbbell in each hand, arms hanging straight down.",
      "Keep your upper arms stationary and curl both dumbbells upward.",
      "Supinate your wrists at the top for maximum bicep contraction.",
      "Lower slowly back to full extension, feeling the stretch at the bottom.",
    ],
    tips: "The incline position stretches the long head of the bicep at the bottom, which is the key advantage of this exercise. Don't let your elbows drift forward — keep them behind your torso throughout.",
  },
  "JM Press": {
    name: "JM Press",
    category: "Arms",
    image: "/exercises/jm_press.webp",
    description: "The JM Press is a hybrid between a close-grip bench press and a skull crusher, providing heavy tricep loading through a unique elbow path.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectorals", "Anterior Deltoids"],
    instructions: [
      "Lie on a flat bench and grip the barbell with a close grip (slightly inside shoulder-width).",
      "Unrack the bar and hold it above your lower chest.",
      "Lower the bar toward your neck/upper chest while allowing your elbows to drift slightly forward.",
      "The bar should travel in a slight arc — not straight down like a bench press.",
      "Press back up to the starting position.",
    ],
    tips: "Start light to learn the elbow path. The movement is a blend of pressing and skull-crushing — your elbows should point forward and slightly out at the bottom. Great for powerlifters building tricep lockout strength.",
  },
  "Landmine Press": {
    name: "Landmine Press",
    category: "Shoulders",
    image: "/exercises/landmine_press.webp",
    description: "The landmine press is a shoulder-friendly pressing variation that follows an arc path, reducing shoulder impingement risk while building pressing strength.",
    primaryMuscles: ["Anterior Deltoids", "Pectorals (upper)"],
    secondaryMuscles: ["Triceps", "Core", "Serratus Anterior"],
    instructions: [
      "Anchor a barbell in a landmine attachment or corner of a wall.",
      "Stand in a split stance and hold the end of the barbell at shoulder height with one hand.",
      "Press the bar upward and forward in an arc until your arm is fully extended.",
      "Lower the bar back to shoulder height under control.",
    ],
    tips: "The arc path of the landmine is more shoulder-friendly than vertical pressing. Keep your core braced to prevent your lower back from arching. Can be done with two hands for a chest-focused variation.",
  },
  "Machine Fly": {
    name: "Machine Fly",
    category: "Chest",
    image: "/exercises/machine_fly.webp",
    description: "The machine fly (pec deck) isolates the pectorals through a horizontal adduction movement with constant resistance throughout the range of motion.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Adjust the seat height so your elbows are at shoulder height when on the pads.",
      "Sit with your back flat against the pad and forearms on the arm pads.",
      "Squeeze your arms together in front of your chest in a controlled arc.",
      "Hold the contracted position briefly, then slowly return to the start.",
    ],
    tips: "Focus on squeezing your chest — not just moving your arms. The machine provides constant tension unlike free-weight flyes. Great as a finishing exercise after compound pressing movements.",
  },
  "Meadows Row": {
    name: "Meadows Row",
    category: "Back",
    image: "/exercises/meadows_row.webp",
    description: "The Meadows Row is a landmine-based single-arm row that allows a unique grip and range of motion, heavily targeting the lats and teres major.",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Rhomboids", "Biceps", "Rear Deltoids"],
    instructions: [
      "Stand perpendicular to a landmine barbell with the loaded end near your feet.",
      "Hinge forward at the hips and grip the end of the barbell with a pronated grip.",
      "Row the bar up toward your hip, driving your elbow back and up.",
      "Lower the bar back to the starting position under control.",
    ],
    tips: "The pronated grip and unique angle of the landmine creates a different stimulus than standard rows. Allow a slight rotation at the top to get a full lat contraction. Use a staggered stance for stability.",
  },
  "Mountain Climbers": {
    name: "Mountain Climbers",
    category: "Cardio",
    image: "/exercises/mountain_climber.webp",
    description: "Mountain climbers are a dynamic full-body exercise combining core stability with cardiovascular conditioning through rapid alternating knee drives.",
    primaryMuscles: ["Core", "Hip Flexors"],
    secondaryMuscles: ["Shoulders", "Chest", "Cardiovascular System"],
    instructions: [
      "Start in a high plank position with hands directly under your shoulders.",
      "Brace your core and keep your hips level throughout.",
      "Drive one knee toward your chest, then quickly switch legs in a running motion.",
      "Maintain a fast pace while keeping your hips from bouncing up and down.",
    ],
    tips: "Keep your hips level — don't let them pike up or sag. The faster you go, the more cardiovascular demand. For a core focus, slow the movement down and hold each knee drive briefly.",
  },
  "Nordic Curls": {
    name: "Nordic Curls",
    category: "Legs",
    image: "/exercises/nordic_curl.webp",
    description: "Nordic curls are one of the most effective hamstring exercises, training the hamstrings eccentrically under extreme load to build strength and prevent injury.",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Calves"],
    instructions: [
      "Kneel on a pad with your feet anchored under a bar or held by a partner.",
      "Keep your body straight from knees to head.",
      "Slowly lower your body forward toward the floor by extending your knees, resisting with your hamstrings.",
      "Catch yourself with your hands, then use your arms to push back to the start.",
    ],
    tips: "This is an extremely difficult exercise — most people can only do 1–3 reps at first. Use your hands to assist the concentric (upward) phase. The eccentric (lowering) phase is where most of the benefit comes from.",
  },
  "Overhead Cable Extensions": {
    name: "Overhead Cable Extensions",
    category: "Arms",
    image: "/exercises/overhead_cable_extension.webp",
    description: "Overhead cable extensions place the triceps in a fully stretched position, maximising the long head activation through a large range of motion.",
    primaryMuscles: ["Triceps Brachii (long head)"],
    secondaryMuscles: ["Triceps (lateral and medial heads)"],
    instructions: [
      "Set a cable pulley to the highest position with a rope attachment.",
      "Face away from the machine and hold the rope behind your head with both hands.",
      "Keep your elbows pointing forward and close to your head.",
      "Extend your arms forward and downward until fully extended.",
      "Return slowly to the starting position.",
    ],
    tips: "Keep your elbows stationary — only your forearms should move. The overhead position maximally stretches the long head of the tricep, which is the largest of the three heads. Great for building tricep mass.",
  },
  "Pallof Press": {
    name: "Pallof Press",
    category: "Core",
    image: "/exercises/pallof_press.webp",
    description: "The Pallof Press is an anti-rotation core exercise that trains the core to resist rotational forces, building functional stability.",
    primaryMuscles: ["Transverse Abdominis", "Obliques"],
    secondaryMuscles: ["Rectus Abdominis", "Glutes"],
    instructions: [
      "Set a cable pulley to chest height and stand sideways to the machine.",
      "Hold the handle at your chest with both hands, feet shoulder-width apart.",
      "Press the handle straight out in front of your chest, resisting the rotational pull.",
      "Hold for 1–2 seconds, then bring it back to your chest.",
    ],
    tips: "The further you stand from the machine, the harder the exercise. Keep your hips square and resist any rotation throughout. This is a stability exercise — the goal is to not rotate, not to create movement.",
  },
  "Pec Deck": {
    name: "Pec Deck",
    category: "Chest",
    image: "/exercises/pec_deck.webp",
    description: "The pec deck machine isolates the pectorals through horizontal adduction with a fixed movement path, providing constant tension throughout the range of motion.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids"],
    instructions: [
      "Adjust the seat so your elbows are at shoulder height when placed on the arm pads.",
      "Sit upright with your back against the pad.",
      "Squeeze the arm pads together in front of your chest.",
      "Hold the peak contraction briefly, then slowly return to the start.",
    ],
    tips: "Focus on feeling the chest squeeze rather than just moving the weight. Don't let the weight stack touch between reps to maintain tension. Great as a finishing movement for a chest workout.",
  },
  "Push-Ups (Deficit)": {
    name: "Push-Ups (Deficit)",
    category: "Chest",
    image: "/exercises/push_up_deficit.webp",
    description: "Deficit push-ups elevate the hands to allow the chest to descend below hand level, increasing the range of motion and pectoral stretch.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps", "Core"],
    instructions: [
      "Place two push-up handles, dumbbells, or plates on the floor at shoulder width.",
      "Assume a push-up position with hands on the elevated handles.",
      "Lower your chest below the level of your hands, feeling a deep pectoral stretch.",
      "Press back up to the starting position.",
    ],
    tips: "The increased range of motion makes this significantly harder than standard push-ups. Start with a small deficit and increase gradually. Keep your core tight and body in a straight line throughout.",
  },
  "Push-Ups (Weighted)": {
    name: "Push-Ups (Weighted)",
    category: "Chest",
    image: "/exercises/push_up_weighted.webp",
    description: "Weighted push-ups add external load to the standard push-up pattern, allowing progressive overload without equipment beyond a weight plate.",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps", "Core"],
    instructions: [
      "Have a partner place a weight plate on your upper back, or use a weighted vest.",
      "Assume a standard push-up position with hands slightly wider than shoulder-width.",
      "Lower your chest to the floor, keeping your body in a straight line.",
      "Press back up to the starting position.",
    ],
    tips: "Start with a light plate (10–25 lbs) and progress gradually. The added weight significantly increases the difficulty. Keep your core braced to prevent your hips from sagging.",
  },
  "Rack Pulls": {
    name: "Rack Pulls",
    category: "Back",
    image: "/exercises/rack_pull.webp",
    description: "Rack pulls are a partial-range deadlift variation starting from knee height, allowing heavier loads to be used to overload the lockout portion of the deadlift.",
    primaryMuscles: ["Spinal Erectors", "Traps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Forearms"],
    instructions: [
      "Set the safety pins in a power rack to just below knee height.",
      "Load the barbell and set up as you would for a deadlift.",
      "Grip the bar and create tension in your lats and upper back.",
      "Drive your hips forward to pull the bar up to a full lockout position.",
      "Lower the bar back to the pins under control.",
    ],
    tips: "Rack pulls allow you to handle significantly more weight than a full deadlift. Focus on the lockout — squeezing your glutes and standing tall at the top. Great for building trap and upper back thickness.",
  },
  "Rear Delt Fly": {
    name: "Rear Delt Fly",
    category: "Shoulders",
    image: "/exercises/rear_delt_fly.webp",
    description: "Rear delt flyes target the posterior deltoids and upper back muscles through a horizontal abduction movement, improving shoulder balance and posture.",
    primaryMuscles: ["Posterior Deltoids"],
    secondaryMuscles: ["Rhomboids", "Middle Trapezius", "Infraspinatus"],
    instructions: [
      "Hinge forward at the hips to about 45–90°, holding dumbbells with arms hanging down.",
      "With a slight bend in the elbows, raise both arms out to the sides in a wide arc.",
      "Lift until your arms are parallel to the floor, squeezing your rear delts.",
      "Lower slowly back to the starting position.",
    ],
    tips: "Lead with your elbows, not your hands. Keep the movement in the horizontal plane — don't shrug or use your traps. Rear delts are often underdeveloped; prioritise them for shoulder health and aesthetics.",
  },
  "Reverse Fly": {
    name: "Reverse Fly",
    category: "Shoulders",
    image: "/exercises/reverse_fly.webp",
    description: "The reverse fly targets the posterior deltoids and rhomboids, helping to counterbalance the overdevelopment of the front deltoids from pressing exercises.",
    primaryMuscles: ["Posterior Deltoids", "Rhomboids"],
    secondaryMuscles: ["Middle Trapezius", "Infraspinatus"],
    instructions: [
      "Hinge forward at the hips, holding dumbbells or cable handles with arms hanging down.",
      "Raise both arms out to the sides with elbows slightly bent.",
      "Lift until your arms are parallel to the floor.",
      "Lower slowly back to the start.",
    ],
    tips: "Use light weight and focus on the rear delt contraction. Avoid using momentum or shrugging. This exercise is essential for shoulder health and posture correction.",
  },
  "Reverse Lunges": {
    name: "Reverse Lunges",
    category: "Legs",
    image: "/exercises/reverse_lunge.webp",
    description: "Reverse lunges are a knee-friendly lunge variation that places less stress on the front knee while effectively targeting the quads, glutes, and hamstrings.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Calves"],
    instructions: [
      "Stand with feet hip-width apart, holding dumbbells at your sides (optional).",
      "Step one foot backward and lower your back knee toward the floor.",
      "Keep your front knee directly over your front foot.",
      "Drive through your front heel to return to the starting position.",
      "Alternate legs or complete all reps on one side.",
    ],
    tips: "Reverse lunges are more knee-friendly than forward lunges because the deceleration forces are reduced. Keep your torso upright throughout. Step back far enough that your front shin is vertical.",
  },
  "Rowing Machine": {
    name: "Rowing Machine",
    category: "Cardio",
    image: "/exercises/rowing_machine.webp",
    description: "The rowing machine (ergometer) provides a full-body cardiovascular workout, engaging the legs, core, and upper body in a coordinated pulling movement.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Back", "Shoulders", "Core"],
    instructions: [
      "Sit on the seat and secure your feet in the foot straps.",
      "Start with legs bent, arms extended forward, and body slightly leaning forward.",
      "Drive through your legs first, then lean back slightly, then pull the handle to your lower chest.",
      "Return in reverse order: extend arms, lean forward, then bend legs.",
    ],
    tips: "The power sequence is 60% legs, 20% back, 20% arms. Many beginners over-rely on their arms. Maintain a smooth, rhythmic stroke. A good starting target is 20–24 strokes per minute.",
  },
  "Seated Cable Row": {
    name: "Seated Cable Row",
    category: "Back",
    image: "/exercises/seated_cable_row.webp",
    description: "The seated cable row is a horizontal pulling exercise that builds mid-back thickness through a full range of motion with constant cable tension.",
    primaryMuscles: ["Rhomboids", "Middle Trapezius", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Spinal Erectors"],
    instructions: [
      "Sit on the cable row bench with feet on the footrests and knees slightly bent.",
      "Grip the close-grip handle with both hands and sit upright.",
      "Pull the handle toward your lower abdomen, driving your elbows back.",
      "Squeeze your shoulder blades together at the end of the movement.",
      "Extend your arms back to the start under control.",
    ],
    tips: "Initiate the pull by retracting your shoulder blades, not by bending your elbows. Allow a slight forward lean at the start to increase range of motion. Keep your lower back neutral throughout.",
  },
  "Seated Calf Raises": {
    name: "Seated Calf Raises",
    category: "Legs",
    image: "/exercises/seated_calf_raise.webp",
    description: "Seated calf raises target the soleus muscle (the deeper calf muscle) which is better activated when the knee is bent, unlike standing calf raises which emphasise the gastrocnemius.",
    primaryMuscles: ["Soleus"],
    secondaryMuscles: ["Gastrocnemius"],
    instructions: [
      "Sit on a seated calf raise machine with the weight pad on your lower thighs.",
      "Place the balls of your feet on the footrest with heels hanging off.",
      "Lower your heels as far as possible for a full stretch.",
      "Raise up on your toes as high as possible, squeezing the calves at the top.",
      "Lower slowly back to the starting position.",
    ],
    tips: "Pause at the bottom for a full stretch and at the top for a full contraction. The soleus responds well to higher rep ranges (15–25 reps). Don't bounce — control the full range of motion.",
  },
  "Seated Leg Curl": {
    name: "Seated Leg Curl",
    category: "Legs",
    image: "/exercises/seated_leg_curl.webp",
    description: "The seated leg curl machine trains the hamstrings in a lengthened position with the hip flexed, which research shows produces greater hamstring hypertrophy than lying leg curls.",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Gastrocnemius"],
    instructions: [
      "Adjust the machine so the pad rests just above your ankles when seated.",
      "Sit upright with your back against the pad and thighs on the seat.",
      "Curl your legs downward against the resistance as far as possible.",
      "Hold the contracted position briefly, then slowly return to the start.",
    ],
    tips: "The seated position keeps the hip flexed, which stretches the hamstrings and increases their activation compared to the lying leg curl. Control the eccentric (return) phase for maximum hypertrophy.",
  },
  "Single-Arm Cable Row": {
    name: "Single-Arm Cable Row",
    category: "Back",
    image: "/exercises/single_arm_cable_row.webp",
    description: "The single-arm cable row allows a greater range of motion and rotation than bilateral rows, improving lat activation and correcting left-right imbalances.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Rhomboids", "Biceps", "Rear Deltoids"],
    instructions: [
      "Set a cable pulley to chest height and attach a D-handle.",
      "Stand or kneel facing the machine, holding the handle in one hand.",
      "Pull the handle toward your hip, rotating your torso slightly and driving your elbow back.",
      "Extend your arm back to the start, allowing a slight forward reach for full lat stretch.",
    ],
    tips: "Allow a slight torso rotation to get a full range of motion and better lat activation. Don't over-rotate — keep the movement controlled. This is great for addressing side-to-side strength imbalances.",
  },
  "Sissy Squats": {
    name: "Sissy Squats",
    category: "Legs",
    image: "/exercises/sissy_squat.webp",
    description: "Sissy squats are an advanced quad isolation exercise that trains the rectus femoris in a lengthened position through a unique knee-dominant movement.",
    primaryMuscles: ["Quadriceps (rectus femoris)"],
    secondaryMuscles: ["Hip Flexors"],
    instructions: [
      "Stand with feet shoulder-width apart, holding a support for balance.",
      "Rise onto your toes and lean your body backward as you bend your knees.",
      "Lower your body by letting your knees travel forward while your torso remains straight.",
      "Descend until your thighs are parallel to the floor or lower.",
      "Drive back up to the starting position.",
    ],
    tips: "This exercise places significant stress on the patellar tendon — start with a limited range of motion and progress slowly. Hold a weight plate to the chest for added resistance. Not recommended for those with knee issues.",
  },
  "Spider Curls": {
    name: "Spider Curls",
    category: "Arms",
    image: "/exercises/spider_curl.webp",
    description: "Spider curls are performed lying face down on an incline bench, placing the biceps in a shortened position at the top for a unique stimulus and peak contraction.",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis"],
    instructions: [
      "Set an incline bench to 45° and lie face down with your chest on the pad.",
      "Hold dumbbells with arms hanging straight down, palms facing forward.",
      "Curl the dumbbells upward toward your shoulders.",
      "Squeeze hard at the top, then lower slowly back to full extension.",
    ],
    tips: "The face-down position prevents any shoulder involvement, making this a pure bicep isolation exercise. The shortened position at the top creates a unique contraction different from standard curls. Great for building the bicep peak.",
  },
  "Stair Climber": {
    name: "Stair Climber",
    category: "Cardio",
    image: "/exercises/stair_climber.webp",
    description: "The stair climber provides a low-impact cardiovascular workout that also builds lower-body muscular endurance, particularly in the glutes and quads.",
    primaryMuscles: ["Cardiovascular System", "Glutes"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Calves"],
    instructions: [
      "Step onto the machine and set your desired speed and duration.",
      "Hold the handrails lightly for balance only — don't lean heavily on them.",
      "Step with full foot contact on each step, pressing through your heel.",
      "Maintain an upright posture throughout.",
    ],
    tips: "Avoid leaning heavily on the handrails — this significantly reduces the caloric burn and glute activation. For more glute emphasis, take longer steps and drive through your heel.",
  },
  "Standing Calf Raises": {
    name: "Standing Calf Raises",
    category: "Legs",
    image: "/exercises/standing_calf_raise.webp",
    description: "Standing calf raises target the gastrocnemius muscle (the larger, visible calf muscle) through plantarflexion with the knee extended.",
    primaryMuscles: ["Gastrocnemius"],
    secondaryMuscles: ["Soleus"],
    instructions: [
      "Stand with the balls of your feet on an elevated surface (step or calf raise platform), heels hanging off.",
      "Hold dumbbells or use a calf raise machine for resistance.",
      "Lower your heels as far as possible for a full stretch.",
      "Rise up on your toes as high as possible, squeezing the calves at the top.",
      "Lower slowly back to the starting position.",
    ],
    tips: "Pause at the bottom for a full stretch — this is where most of the growth stimulus comes from. The gastrocnemius is a stubborn muscle that responds well to high volume (4–6 sets, 15–20 reps).",
  },
  "Step-Ups": {
    name: "Step-Ups",
    category: "Legs",
    image: "/exercises/step_up.webp",
    description: "Step-ups are a unilateral lower-body exercise that builds quad and glute strength while improving balance and correcting left-right imbalances.",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    instructions: [
      "Stand facing a box or bench, holding dumbbells at your sides.",
      "Step one foot onto the box and drive through that heel to lift your body up.",
      "Bring your other foot up to meet the first foot on the box.",
      "Step back down with the same foot you started with.",
      "Complete all reps on one side before switching.",
    ],
    tips: "Drive through the heel of the elevated foot — don't push off the back foot. The higher the box, the more glute activation. Keep your torso upright throughout the movement.",
  },
  "Stiff-Leg Deadlifts": {
    name: "Stiff-Leg Deadlifts",
    category: "Back",
    image: "/exercises/stiff_leg_deadlift.webp",
    description: "Stiff-leg deadlifts are a hamstring and lower back exercise that maintains near-straight legs throughout, maximising the hip hinge range of motion.",
    primaryMuscles: ["Hamstrings", "Spinal Erectors"],
    secondaryMuscles: ["Glutes", "Traps", "Forearms"],
    instructions: [
      "Stand with feet hip-width apart, holding a barbell with an overhand grip.",
      "Keep a slight bend in your knees and hinge at the hips, pushing them backward.",
      "Lower the bar along your legs, keeping it close to your body.",
      "Lower until you feel a strong hamstring stretch, keeping your back flat.",
      "Drive your hips forward to return to the starting position.",
    ],
    tips: "Unlike Romanian deadlifts, stiff-leg deadlifts allow the bar to travel further down (sometimes to the floor). Keep your back flat — never round. Feel the hamstring stretch at the bottom of each rep.",
  },
  "Straight-Arm Pulldown": {
    name: "Straight-Arm Pulldown",
    category: "Back",
    image: "/exercises/straight_arm_pulldown.webp",
    description: "The straight-arm pulldown isolates the lats through shoulder extension with straight arms, eliminating bicep involvement for a pure lat contraction.",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Teres Major", "Posterior Deltoids", "Core"],
    instructions: [
      "Stand facing a high cable pulley with a straight bar or rope attachment.",
      "Grip the bar with arms extended at shoulder height.",
      "Keep your arms straight and pull the bar downward in an arc toward your thighs.",
      "Squeeze your lats hard at the bottom, then slowly return to the start.",
    ],
    tips: "Keep your arms completely straight throughout — any elbow bend brings the biceps into the movement. Lean forward slightly for a better lat stretch at the top. This is excellent for learning to feel your lats.",
  },
  "Swimming": {
    name: "Swimming",
    category: "Cardio",
    image: "/exercises/swimming.webp",
    description: "Swimming is a full-body, zero-impact cardiovascular exercise that builds endurance, upper-body strength, and flexibility simultaneously.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Shoulders", "Back", "Core", "Legs"],
    instructions: [
      "Warm up with easy laps before increasing intensity.",
      "Focus on technique — a streamlined body position reduces drag.",
      "For freestyle: rotate your body with each stroke and breathe to the side.",
      "Use interval training (e.g., sprint 50m, rest 30 seconds) for higher intensity.",
    ],
    tips: "Swimming technique is critical — poor form wastes energy. Consider a few lessons if you're a beginner. Use different strokes (freestyle, backstroke, breaststroke) to vary the muscle demands.",
  },
  "T-Bar Row": {
    name: "T-Bar Row",
    category: "Back",
    image: "/exercises/t_bar_row.webp",
    description: "The T-bar row is a heavy compound back exercise that allows significant loading of the mid-back muscles through a supported rowing motion.",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Spinal Erectors"],
    instructions: [
      "Straddle the T-bar machine or landmine setup and grip the handles.",
      "Hinge forward at the hips to about 45°, keeping your back flat.",
      "Row the bar toward your chest, driving your elbows back and squeezing your shoulder blades.",
      "Lower the bar back to the starting position under control.",
    ],
    tips: "Use a chest-supported T-bar row if lower back fatigue is an issue. Drive your elbows back rather than just pulling with your arms. A close grip targets the mid-back; a wider grip hits more of the outer lats.",
  },
  "Tate Press": {
    name: "Tate Press",
    category: "Arms",
    image: "/exercises/tate_press.png",
    description: "The Tate Press is a dumbbell tricep exercise performed lying on a bench, where the elbows flare outward as the dumbbells lower toward the chest.",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Pectorals"],
    instructions: [
      "Lie on a flat bench holding dumbbells above your chest, palms facing your feet.",
      "Keeping your upper arms stationary, lower the dumbbells by bending your elbows outward.",
      "Lower until the dumbbells nearly touch your chest.",
      "Extend your elbows to press back up to the starting position.",
    ],
    tips: "The outward elbow flare is what distinguishes this from a close-grip press. Use moderate weight and focus on the tricep contraction. Great as an accessory exercise for powerlifters.",
  },
  "Tibialis Raises": {
    name: "Tibialis Raises",
    category: "Legs",
    image: "/exercises/tibialis_raise.png",
    description: "Tibialis raises strengthen the tibialis anterior muscle on the front of the shin, improving ankle stability and helping prevent shin splints.",
    primaryMuscles: ["Tibialis Anterior"],
    secondaryMuscles: ["Ankle Stabilisers"],
    instructions: [
      "Stand with your back against a wall and heels about 6 inches from the wall.",
      "Keep your legs straight and raise your toes and forefoot as high as possible.",
      "Hold briefly at the top, then lower slowly back to the floor.",
      "Perform 15–25 reps per set.",
    ],
    tips: "This is a preventive and rehabilitation exercise often overlooked in training. Strengthening the tibialis anterior helps prevent shin splints and improves running economy. Can be loaded with a weight on the foot.",
  },
  "Upright Rows": {
    name: "Upright Rows",
    category: "Shoulders",
    image: "/exercises/upright_row.webp",
    description: "Upright rows build the lateral deltoids and upper traps through a vertical pulling motion, though they require careful technique to avoid shoulder impingement.",
    primaryMuscles: ["Lateral Deltoids", "Upper Trapezius"],
    secondaryMuscles: ["Anterior Deltoids", "Biceps"],
    instructions: [
      "Stand holding a barbell or dumbbells with an overhand grip, hands shoulder-width apart.",
      "Pull the bar straight up along your body toward your chin, leading with your elbows.",
      "Raise until your elbows are at shoulder height or slightly above.",
      "Lower the bar back to the starting position under control.",
    ],
    tips: "Use a wider grip to reduce shoulder impingement risk. Stop when your elbows reach shoulder height — going higher increases impingement risk. Dumbbells allow a more natural wrist path than a barbell.",
  },
  "Y-Raises": {
    name: "Y-Raises",
    category: "Shoulders",
    image: "/exercises/y_raise.webp",
    description: "Y-raises target the lower trapezius and posterior deltoids, which are crucial for shoulder health, posture, and scapular stability.",
    primaryMuscles: ["Lower Trapezius", "Posterior Deltoids"],
    secondaryMuscles: ["Rhomboids", "Infraspinatus"],
    instructions: [
      "Lie face down on an incline bench or stand bent forward at the hips.",
      "Hold very light dumbbells with arms hanging down.",
      "Raise both arms upward and outward at 45° to form a Y shape.",
      "Squeeze your lower traps at the top, then lower slowly.",
    ],
    tips: "Use very light weight — this targets small stabiliser muscles. Focus on the lower trap contraction, not just raising your arms. Y-raises are excellent for shoulder health and correcting upper-cross syndrome.",
  },
  "Running": {
    name: "Running",
    category: "Cardio",
    image: "/exercises/running.webp",
    description: "Running is the most accessible cardio exercise, improving cardiovascular fitness, endurance, and caloric expenditure.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    instructions: [
      "Start with a 5-minute warm-up walk before increasing to your target pace.",
      "Maintain an upright posture with a slight forward lean from the ankles.",
      "Land with your foot under your centre of mass, not out in front.",
      "Keep your arms relaxed at roughly 90° and swing them forward-backward, not across your body.",
      "Cool down with a 5-minute walk and stretch afterward.",
    ],
    tips: "For beginners, use a run/walk interval approach (e.g., 1 min run, 2 min walk) and gradually increase running time. Proper footwear is essential to prevent injury. Track your pace and aim for conversational effort on easy days.",
  },
  "Jump Rope": {
    name: "Jump Rope",
    category: "Cardio",
    image: "/exercises/jump_rope.webp",
    description: "Jump rope is a high-intensity cardio exercise that builds coordination, footwork, and cardiovascular fitness.",
    primaryMuscles: ["Cardiovascular System"],
    secondaryMuscles: ["Calves", "Shoulders", "Core"],
    instructions: [
      "Hold the rope handles at hip height with elbows close to your sides.",
      "Start with small wrist rotations to swing the rope over your head.",
      "Jump with both feet together, clearing the rope by just a few centimetres.",
      "Land softly on the balls of your feet with knees slightly bent.",
      "Maintain a steady rhythm and keep your core engaged.",
    ],
    tips: "Start with basic two-foot jumps before progressing to alternating feet or double-unders. Jump on a forgiving surface like a rubber mat. Keep jumps low and efficient — you only need to clear the rope.",
  },
};

/**
 * Aliases: maps exercise names from exercises.ts to keys in EXERCISE_DETAILS
 */
const EXERCISE_ALIASES: Record<string, string> = {
  // Back
  "Lat Pulldown": "Lat Pulldowns",
  "Seated Cable Row": "Cable Rows",
  // Chest
  "Chest Flyes": "Chest Flyes",
  "Incline Bench Press": "Incline Bench Press",
  // Arms
  "Skull Crushers": "Skull Crushers",
  "Tricep Extensions": "Tricep Extensions",
  // Legs
  "Leg Extensions": "Leg Extensions",
  "Calf Raises": "Calf Raises",
  "Standing Calf Raises": "Calf Raises",
  "Seated Calf Raises": "Calf Raises",
  // Shoulders
  "Lateral Raise": "Lateral Raises",
  "Front Raise": "Front Raises",
  "Overhead Press": "Overhead Press",
  // Core
  "Plank": "Planks",
  "Russian Twist": "Russian Twists",
  "Hanging Leg Raise": "Hanging Leg Raises",
};

/**
 * Get exercise detail by exercise name (case-insensitive, alias-aware)
 */
export function getExerciseDetail(name: string): ExerciseDetail | undefined {
  // Exact match first
  if (EXERCISE_DETAILS[name]) return EXERCISE_DETAILS[name];
  // Alias match
  const aliasKey = EXERCISE_ALIASES[name];
  if (aliasKey && EXERCISE_DETAILS[aliasKey]) return EXERCISE_DETAILS[aliasKey];
  // Case-insensitive match
  const lower = name.toLowerCase();
  const key = Object.keys(EXERCISE_DETAILS).find(k => k.toLowerCase() === lower);
  if (key) return EXERCISE_DETAILS[key];
  // Case-insensitive alias match
  const aliasKeyCI = Object.keys(EXERCISE_ALIASES).find(k => k.toLowerCase() === lower);
  if (aliasKeyCI) {
    const resolved = EXERCISE_ALIASES[aliasKeyCI];
    if (EXERCISE_DETAILS[resolved]) return EXERCISE_DETAILS[resolved];
  }
  return undefined;
}
