"""
Generates the cardio runner graphic and writes it as a TypeScript export.
Output: client/src/lib/cardioGraphicB64.ts
Run from project root: python3.11 scripts/makeCardioGraphicTS.py
"""
import base64, io
from PIL import Image, ImageDraw, ImageFilter

W, H = 920, 640
img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
d = ImageDraw.Draw(img)

cx, cy = W // 2 + 70, H // 2 + 10
R_OUTER = 255
R_INNER = 210

d.ellipse([cx-R_OUTER, cy-R_OUTER, cx+R_OUTER, cy+R_OUTER], fill=(59,130,246,20))
d.ellipse([cx-R_INNER, cy-R_INNER, cx+R_INNER, cy+R_INNER], fill=(0,0,0,0))

for r in range(R_INNER+4, R_OUTER-4, 3):
    d.arc([cx-r, cy-r, cx+r, cy+r], start=-90, end=180, fill=(59,130,246,185), width=3)

sx = cx - R_OUTER - 5
for i, (y_off, length, alpha, lw) in enumerate([
    (-105, 270, 145, 6), (-58, 310, 165, 5), (-10, 330, 185, 5),
    (38,  300, 165, 4),  (85,  250, 135, 3), (128, 195, 105, 2),
]):
    d.line([sx, cy + y_off, sx - length, cy + y_off], fill=(59,130,246,alpha), width=lw)
    d.line([sx - length, cy + y_off, sx - length - 45, cy + y_off],
           fill=(59,130,246, alpha // 4), width=max(1, lw - 1))

S = 0.88
rx, ry = cx, cy + 30

def pt(dx, dy):
    return (rx + int(dx * S), ry + int(dy * S))

def poly(*coords, alpha=220):
    d.polygon([pt(x, y) for x, y in coords], fill=(59,130,246,alpha))

def ell(x0, y0, x1, y1, alpha=225):
    p = [pt(x0,y0), pt(x1,y1)]
    d.ellipse([p[0][0], p[0][1], p[1][0], p[1][1]], fill=(59,130,246,alpha))

ell(-20, -215, 20, -167, alpha=235)
poly((-5,-167),(5,-167),(4,-148),(-4,-148), alpha=225)
poly((-16,-125),(12,-125),(22,-18),(-10,-18), alpha=225)
poly((-12,-108),(2,-96),(-58,-28),(-72,-40), alpha=215)
poly((-58,-28),(-72,-40),(-100,15),(-86,27), alpha=205)
poly((8,-108),(22,-96),(68,-162),(54,-174), alpha=215)
poly((68,-162),(54,-174),(82,-205),(96,-193), alpha=205)
poly((-10,-18),(4,-18),(-28,88),(-42,88), alpha=225)
poly((-28,88),(-42,88),(-78,178),(-64,178), alpha=215)
poly((-78,178),(-64,178),(-50,192),(-95,192), alpha=205)
poly((4,-18),(18,-18),(60,72),(46,72), alpha=225)
poly((46,72),(60,72),(52,162),(38,162), alpha=215)
poly((38,162),(52,162),(72,176),(28,176), alpha=205)

glow = Image.new("RGBA", (W, H), (0,0,0,0))
gd = ImageDraw.Draw(glow)
p0, p1 = pt(-110, 192), pt(90, 205)
gd.ellipse([p0[0], p0[1], p1[0], p1[1]], fill=(59,130,246,40))
glow = glow.filter(ImageFilter.GaussianBlur(15))
img = Image.alpha_composite(img, glow)

buf = io.BytesIO()
img.save(buf, format="PNG")
b64 = base64.b64encode(buf.getvalue()).decode()
data_uri = "data:image/png;base64," + b64

ts_content = (
    "// Auto-generated by scripts/makeCardioGraphicTS.py — DO NOT EDIT\n"
    f'export const CARDIO_GRAPHIC_B64 = "{data_uri}";\n'
)
with open("client/src/lib/cardioGraphicB64.ts", "w") as f:
    f.write(ts_content)

print(f"Written client/src/lib/cardioGraphicB64.ts ({len(b64)} chars base64)")
