/**
 * Generates preview PNGs for three workout card scenarios:
 *   1. Pure strength (weights only)
 *   2. Pure cardio (running + cycling)
 *   3. Mixed (weights + cardio)
 *
 * Run: npx tsx scripts/previewCards.ts
 * Output: scripts/preview-*.png
 */

import { writeFileSync, readFileSync } from "fs";
import { INTER_REGULAR_B64, INTER_BOLD_B64 } from "../server/fontData.js";
import { FLEXTAB_ICON_B64, FLEXTAB_ICON_WHITE_B64 } from "../client/src/lib/flextabIconB64.js";

// Cardio graphic (runner + ring) — generated by scripts/makeCardioGraphic.py
const CARDIO_GRAPHIC_URI = readFileSync(new URL("./cardio_graphic.b64", import.meta.url), "utf8");

// ── Story canvas ──────────────────────────────────────────────────────────────
const STORY_W = 1080;
const STORY_H = 1920;
const PAD_H   = 80;
const PAD_TOP = 120;
const PAD_BOT = 260;
const USABLE_H   = STORY_H - PAD_TOP - PAD_BOT;
const CONTENT_W  = STORY_W - PAD_H * 2;

// ── Theme ─────────────────────────────────────────────────────────────────────
const THEMES = {
  light: {
    bg:           "linear-gradient(160deg, #e8edf6 0%, #dce4f0 40%, #cdd8ec 100%)",
    tileBg:       "rgba(255,255,255,0.80)",
    divider:      "rgba(15,23,42,0.10)",
    textPrimary:  "#0f172a",
    textMuted:    "#64748b",
    textFooter:   "#94a3b8",
    badgeBg:      "#0f172a",
    badgeText:    "#ffffff",
    chipBg:       "rgba(15,23,42,0.06)",
    cardioBg:     "rgba(59,130,246,0.10)",
    cardioAccent: "#3b82f6",
    setNumColor:  "#1e3a5f",
    setNumWeight: 700,
    exHeaderBg:   "rgba(15,23,42,0.07)",
    accentBar:    "#0f172a",
    setsBadgeBg:  "rgba(15,23,42,0.10)",
  },
  dark: {
    bg:           "linear-gradient(160deg, #0a0f1e 0%, #0d1526 50%, #060b16 100%)",
    tileBg:       "rgba(255,255,255,0.06)",
    divider:      "rgba(255,255,255,0.08)",
    textPrimary:  "#f1f5f9",
    textMuted:    "#64748b",
    textFooter:   "#334155",
    badgeBg:      "rgba(255,255,255,0.12)",
    badgeText:    "#f1f5f9",
    chipBg:       "rgba(255,255,255,0.06)",
    cardioBg:     "rgba(59,130,246,0.15)",
    cardioAccent: "#3b82f6",
    setNumColor:  "#94a3b8",
    setNumWeight: 600,
    exHeaderBg:   "rgba(255,255,255,0.06)",
    accentBar:    "#3b82f6",
    setsBadgeBg:  "rgba(255,255,255,0.10)",
  },
} as const;

type Theme = keyof typeof THEMES;

// ── Data interfaces ───────────────────────────────────────────────────────────
interface SetDetail { setNumber: number; reps: number; weight: number; }
interface ExerciseRow {
  exercise: string;
  totalSets: number;
  bestReps: number;
  bestWeight: number;
  category: string;
  volume: number;
  sets?: SetDetail[];
  duration?: number;   // seconds
  distance?: number;
  distanceUnit?: "miles" | "km";
}
interface CardData {
  date: string;
  duration?: string;
  totalSets: number;
  totalReps: number;
  volumeDisplay: string;
  exercises: ExerciseRow[];
  theme?: Theme;
  userName?: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function truncate(s: string, max: number) {
  return s.length > max ? s.slice(0, max - 1) + "…" : s;
}

function isCardio(ex: ExerciseRow) {
  return (ex.distance != null && ex.distance > 0) || (ex.duration != null && ex.duration > 0 && (ex.sets == null || ex.sets.length === 0));
}

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function formatPace(durationSec: number, distance: number, unit: string): string {
  if (!distance || !durationSec) return "—";
  const paceSecPerUnit = durationSec / distance;
  const m = Math.floor(paceSecPerUnit / 60);
  const s = Math.round(paceSecPerUnit % 60);
  return `${m}:${String(s).padStart(2, "0")}/${unit}`;
}

// ── Layout constants ──────────────────────────────────────────────────────────
const CHIPS_PER_ROW = 3;
const CHIP_GAP      = 14;
const H_HEADER      = 88 + 28;
const H_TILE_ROW    = 120;
const H_TILE_GAP    = 12;
const H_STAT_STRIP  = H_TILE_ROW * 2 + H_TILE_GAP;
const H_STAT_MB     = 24;
const H_DIVIDER     = 1 + 16;
const H_SECTION_LBL = 26 + 16;
const H_FOOTER      = 1 + 16 + 26 + 14;
const H_EX_HEADER   = 72 + 12;
const H_EX_GAP      = 20;
const H_CARDIO_CHIP = 110; // fixed height for cardio info block

const H_CHROME = H_HEADER + H_STAT_STRIP + H_STAT_MB + H_DIVIDER + H_SECTION_LBL + H_FOOTER;

function computeChipH(exercises: ExerciseRow[]): number {
  const strengthExercises = exercises.filter(ex => !isCardio(ex));
  if (strengthExercises.length === 0) return 90;

  const numEx = exercises.length;
  // Cardio exercises contribute a fixed H_CARDIO_CHIP height (no variable chip rows)
  const cardioFixedH = exercises.filter(isCardio).reduce((sum) => sum + H_CARDIO_CHIP + CHIP_GAP, 0);

  const totalChipRows = strengthExercises.reduce((sum, ex) => {
    const n = ex.sets?.length ?? ex.totalSets;
    return sum + Math.ceil(n / CHIPS_PER_ROW);
  }, 0);
  const extraChipGaps = strengthExercises.reduce((sum, ex) => {
    const n = ex.sets?.length ?? ex.totalSets;
    const rows = Math.ceil(n / CHIPS_PER_ROW);
    return sum + Math.max(0, rows - 1) * CHIP_GAP;
  }, 0);
  const fixedExercise = numEx * H_EX_HEADER + (numEx - 1) * H_EX_GAP + extraChipGaps + cardioFixedH;
  const available = USABLE_H - H_CHROME - fixedExercise;
  if (totalChipRows === 0) return 90;
  const chipH = Math.floor(available / totalChipRows);
  return Math.max(70, Math.min(150, chipH));
}

// ── Stat strip builder ────────────────────────────────────────────────────────
function buildStatStrip(data: CardData, C: typeof THEMES.dark) {
  const pureCardio = data.exercises.every(isCardio);

  let stats: Array<{ v: string; l: string }>;

  if (pureCardio) {
    // Aggregate cardio stats
    const totalDistKm = data.exercises.reduce((s, ex) => {
      if (!ex.distance) return s;
      return s + (ex.distanceUnit === "miles" ? ex.distance * 1.60934 : ex.distance);
    }, 0);
    const totalDistMi = data.exercises.reduce((s, ex) => {
      if (!ex.distance) return s;
      return s + (ex.distanceUnit === "miles" ? ex.distance : ex.distance / 1.60934);
    }, 0);
    const totalDurSec = data.exercises.reduce((s, ex) => s + (ex.duration ?? 0), 0);
    const distDisplay = totalDistKm > 0
      ? `${totalDistKm.toFixed(1)} km`
      : "—";
    const paceDisplay = totalDurSec > 0 && totalDistKm > 0
      ? formatPace(totalDurSec, totalDistKm, "km")
      : "—";
    stats = [
      { v: data.duration || "—",            l: "DURATION" },
      { v: distDisplay,                      l: "DISTANCE" },
      { v: paceDisplay,                      l: "AVG PACE" },
      { v: String(data.exercises.length),    l: "ACTIVITIES" },
    ];
  } else {
    stats = [
      { v: data.duration || "—",   l: "DURATION" },
      { v: String(data.totalSets), l: "SETS"     },
      { v: String(data.totalReps), l: "REPS"     },
      { v: data.volumeDisplay,     l: "VOLUME"   },
    ];
  }

  const tileEl = (s: { v: string; l: string }, isRight: boolean) => ({
    type: "div",
    props: {
      style: {
        flex: 1, display: "flex", flexDirection: "column",
        alignItems: "center", justifyContent: "center",
        background: C.tileBg, borderRadius: 20,
        height: H_TILE_ROW,
        marginLeft: isRight ? H_TILE_GAP : 0,
      },
      children: [
        { type: "div", props: { style: { fontSize: 52, fontWeight: 800, color: C.textPrimary, lineHeight: 1, display: "flex" }, children: s.v } },
        { type: "div", props: { style: { fontSize: 20, fontWeight: 700, color: C.textMuted, marginTop: 8, letterSpacing: "0.10em", display: "flex" }, children: s.l } },
      ],
    },
  });

  return {
    type: "div",
    props: {
      style: { display: "flex", flexDirection: "column", gap: H_TILE_GAP, marginBottom: H_STAT_MB },
      children: [
        { type: "div", props: { style: { display: "flex", flexDirection: "row" }, children: [tileEl(stats[0], false), tileEl(stats[1], true)] } },
        { type: "div", props: { style: { display: "flex", flexDirection: "row" }, children: [tileEl(stats[2], false), tileEl(stats[3], true)] } },
      ],
    },
  };
}

// ── Cardio info block ─────────────────────────────────────────────────────────
function buildCardioBlock(ex: ExerciseRow, C: typeof THEMES.dark) {
  const distStr = ex.distance
    ? `${ex.distance} ${ex.distanceUnit ?? "km"}`
    : null;
  const durStr = ex.duration ? formatDuration(ex.duration) : null;
  const paceStr = ex.duration && ex.distance
    ? formatPace(ex.duration, ex.distance, ex.distanceUnit ?? "km")
    : null;

  const statItems: Array<{ v: string; l: string }> = [];
  if (durStr)  statItems.push({ v: durStr,  l: "DURATION" });
  if (distStr) statItems.push({ v: distStr, l: "DISTANCE" });
  if (paceStr) statItems.push({ v: paceStr, l: "PACE" });

  // Fill to 3 slots
  while (statItems.length < 3) statItems.push({ v: "—", l: "" });

  const slotW = Math.floor((CONTENT_W - 2 * CHIP_GAP) / 3);

  return {
    type: "div",
    props: {
      style: {
        display: "flex", flexDirection: "row", gap: CHIP_GAP,
        height: H_CARDIO_CHIP,
      },
      children: statItems.map(s => ({
        type: "div",
        props: {
          style: {
            width: slotW, height: H_CARDIO_CHIP,
            background: C.cardioBg,
            borderRadius: 14,
            display: "flex", flexDirection: "column",
            justifyContent: "center", alignItems: "center",
            gap: 6,
          },
          children: [
            { type: "div", props: { style: { fontSize: 36, fontWeight: 800, color: C.cardioAccent, display: "flex", lineHeight: 1 }, children: s.v } },
            { type: "div", props: { style: { fontSize: 18, fontWeight: 700, color: C.textMuted, letterSpacing: "0.10em", display: "flex" }, children: s.l } },
          ],
        },
      })),
    },
  };
}

// ── Card builder ──────────────────────────────────────────────────────────────
function buildCard(data: CardData) {
  const C      = THEMES[data.theme === "dark" ? "dark" : "light"];
  const isDark = data.theme === "dark";
  const { date, exercises, userName } = data;

  const chipH = computeChipH(exercises);
  const chipValueFontSize = Math.round(chipH * 0.44);
  const chipLabelFontSize = Math.round(chipH * 0.22);
  const chipUnitFontSize  = Math.round(chipH * 0.22);

  // ── Header ──────────────────────────────────────────────────────────────────
  const headerEl = {
    type: "div",
    props: {
      style: { display: "flex", alignItems: "center", gap: 20, marginBottom: 28 },
      children: [
        { type: "img", props: { src: isDark ? FLEXTAB_ICON_WHITE_B64 : FLEXTAB_ICON_B64, width: 72, height: 72, style: { borderRadius: 18, flexShrink: 0 } } },
        {
          type: "div",
          props: {
            style: { display: "flex", flexDirection: "column", gap: 4, flex: 1 },
            children: [
              { type: "div", props: { style: { fontSize: 42, fontWeight: 800, color: C.textPrimary, display: "flex" }, children: "FlexTab" } },
              { type: "div", props: { style: { fontSize: 26, color: C.textMuted, display: "flex" }, children: date } },
            ],
          },
        },
      ],
    },
  };

  // ── Stat strip ───────────────────────────────────────────────────────────────
  const statStripEl = buildStatStrip(data, C);

  // ── Exercises ────────────────────────────────────────────────────────────────
  const exerciseEls = exercises.map((ex, ei) => {
    const cardio = isCardio(ex);
    const sets = ex.sets ?? [];
    const chipRows: SetDetail[][] = [];
    if (!cardio) {
      for (let i = 0; i < sets.length; i += CHIPS_PER_ROW) {
        chipRows.push(sets.slice(i, i + CHIPS_PER_ROW));
      }
    }

    const fixedChipW = Math.floor((CONTENT_W - (CHIPS_PER_ROW - 1) * CHIP_GAP) / CHIPS_PER_ROW);

    const chipRowEls = chipRows.map((row, ri) => ({
      type: "div",
      props: {
        style: { display: "flex", flexDirection: "row", gap: CHIP_GAP, marginTop: ri === 0 ? 0 : CHIP_GAP },
        children: row.map(s => ({
          type: "div",
          props: {
            style: {
              width: fixedChipW, height: chipH,
              background: C.chipBg, borderRadius: 14,
              display: "flex", flexDirection: "column",
              justifyContent: "center", paddingLeft: 14, paddingRight: 10, gap: 2,
            },
            children: [
              { type: "div", props: { style: { fontSize: chipLabelFontSize, fontWeight: C.setNumWeight, color: C.setNumColor, display: "flex" }, children: `Set ${s.setNumber}` } },
              {
                type: "div",
                props: {
                  style: { display: "flex", alignItems: "baseline", gap: 4 },
                  children: [
                    { type: "div", props: { style: { fontSize: chipValueFontSize, fontWeight: 800, color: C.textPrimary, display: "flex", lineHeight: 1 }, children: String(s.reps) } },
                    { type: "div", props: { style: { fontSize: chipUnitFontSize, fontWeight: 400, color: C.textMuted, display: "flex" }, children: " reps" } },
                    ...(s.weight > 0 ? [
                      { type: "div", props: { style: { fontSize: chipUnitFontSize, fontWeight: 400, color: C.textMuted, display: "flex" }, children: " · " } },
                      { type: "div", props: { style: { fontSize: chipValueFontSize, fontWeight: 800, color: C.textPrimary, display: "flex", lineHeight: 1 }, children: String(s.weight) } },
                      { type: "div", props: { style: { fontSize: chipUnitFontSize, fontWeight: 400, color: C.textMuted, display: "flex" }, children: " lbs" } },
                    ] : []),
                  ],
                },
              },
            ],
          },
        })),
      },
    }));

    // Header badge label — for cardio show activity type
    const badgeLabel = cardio ? "🏃" : String(ei + 1);
    const rightBadge = cardio
      ? null
      : {
          type: "div",
          props: {
            style: { background: C.setsBadgeBg, borderRadius: 50, paddingLeft: 20, paddingRight: 20, paddingTop: 8, paddingBottom: 8, marginRight: 16, display: "flex", flexShrink: 0 },
            children: { type: "div", props: { style: { fontSize: 22, fontWeight: 700, color: C.textMuted, display: "flex", whiteSpace: "nowrap" }, children: `${ex.totalSets} sets` } },
          },
        };

    return {
      type: "div",
      props: {
        style: { display: "flex", flexDirection: "column", marginTop: ei === 0 ? 0 : H_EX_GAP },
        children: [
          // Exercise header band
          {
            type: "div",
            props: {
              style: {
                display: "flex", alignItems: "center",
                background: cardio ? C.cardioBg : C.exHeaderBg,
                borderRadius: 16, height: 72, marginBottom: 12,
                overflow: "hidden", paddingLeft: 20,
                borderBottom: `2px solid ${cardio ? C.cardioAccent : C.accentBar}`,
              },
              children: [
                { type: "div", props: { style: { width: 52, height: 52, borderRadius: 26, background: C.badgeBg, color: C.badgeText, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, fontWeight: 800, flexShrink: 0 }, children: String(ei + 1) } },
                { type: "div", props: { style: { flex: 1, fontSize: 40, fontWeight: 800, color: C.textPrimary, display: "flex", marginLeft: 16, letterSpacing: "-0.01em" }, children: truncate(ex.exercise, 26) } },
                ...(rightBadge ? [rightBadge] : []),
              ],
            },
          },
          // Cardio info block or strength chip rows
          ...(cardio ? [buildCardioBlock(ex, C)] : chipRowEls),
        ],
      },
    };
  });

  // ── Footer ───────────────────────────────────────────────────────────────────
  const footerText = userName
    ? `@${userName.toLowerCase().replace(/\s+/g, "")} · flextab.app`
    : "flextab.app";

  const footerEl = {
    type: "div",
    props: {
      style: {
        display: "flex", alignItems: "center", justifyContent: "center",
        marginTop: "auto", paddingTop: 16,
        borderTop: `1px solid ${C.divider}`,
      },
      children: { type: "div", props: { style: { fontSize: 26, color: C.textFooter, fontWeight: 600, display: "flex" }, children: footerText } },
    },
  };

  // ── Cardio graphic filler (pure-cardio only) ───────────────────────────────
  const pureCardio = exercises.every(isCardio);
  const cardioGraphicEl = pureCardio ? {
    type: "div",
    props: {
      style: {
        display: "flex", flex: 1,
        alignItems: "center", justifyContent: "center",
        marginTop: 24,
      },
      children: [
        {
          type: "img",
          props: {
            src: CARDIO_GRAPHIC_URI,
            width: CONTENT_W,
            height: Math.round(CONTENT_W * 640 / 920),
            style: { opacity: 0.92 },
          },
        },
      ],
    },
  } : null;

  return {
    type: "div",
    props: {
      style: {
        display: "flex", flexDirection: "column",
        width: STORY_W, height: STORY_H,
        background: C.bg,
        paddingTop: PAD_TOP, paddingBottom: PAD_BOT,
        paddingLeft: PAD_H, paddingRight: PAD_H,
      },
      children: [
        headerEl,
        statStripEl,
        { type: "div", props: { style: { height: 1, background: C.divider, marginBottom: 16, display: "flex" } } },
        { type: "div", props: { style: { fontSize: 22, fontWeight: 800, color: C.textMuted, textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 12, display: "flex" }, children: "EXERCISES" } },
        { type: "div", props: { style: { display: "flex", flexDirection: "column" }, children: exerciseEls } },
        ...(cardioGraphicEl ? [cardioGraphicEl] : []),
        footerEl,
      ],
    },
  };
}

// ── Render helper ─────────────────────────────────────────────────────────────
async function render(data: CardData, outPath: string) {
  const { default: satori } = await import("satori");
  const { Resvg }           = await import("@resvg/resvg-js");

  const fontRegular = Buffer.from(INTER_REGULAR_B64, "base64");
  const fontBold    = Buffer.from(INTER_BOLD_B64,    "base64");

  const satoriOpts = {
    width: STORY_W, height: STORY_H,
    fonts: [
      { name: "Inter", data: fontRegular, weight: 400 as const, style: "normal" as const },
      { name: "Inter", data: fontBold,    weight: 700 as const, style: "normal" as const },
      { name: "Inter", data: fontBold,    weight: 800 as const, style: "normal" as const },
    ],
  };

  const svg       = await satori(buildCard(data) as any, satoriOpts);
  const resvg     = new Resvg(svg, { fitTo: { mode: "width", value: STORY_W } });
  const pngBuffer = resvg.render().asPng();
  writeFileSync(outPath, pngBuffer);
  console.log(`✓ ${outPath}`);
}

// ── Sample data ───────────────────────────────────────────────────────────────

// 1. Pure strength
const strengthData: CardData = {
  date: "Wednesday, Mar 18, 2025",
  duration: "52 min",
  totalSets: 12,
  totalReps: 96,
  volumeDisplay: "14.2k",
  theme: "dark",
  userName: "alexfit",
  exercises: [
    {
      exercise: "Bench Press",
      totalSets: 4, bestReps: 8, bestWeight: 185, category: "Chest", volume: 5920,
      sets: [
        { setNumber: 1, reps: 10, weight: 155 },
        { setNumber: 2, reps: 8,  weight: 175 },
        { setNumber: 3, reps: 8,  weight: 185 },
        { setNumber: 4, reps: 6,  weight: 185 },
      ],
    },
    {
      exercise: "Incline Dumbbell Press",
      totalSets: 3, bestReps: 10, bestWeight: 70, category: "Chest", volume: 2100,
      sets: [
        { setNumber: 1, reps: 12, weight: 60 },
        { setNumber: 2, reps: 10, weight: 70 },
        { setNumber: 3, reps: 10, weight: 70 },
      ],
    },
    {
      exercise: "Cable Fly",
      totalSets: 3, bestReps: 12, bestWeight: 40, category: "Chest", volume: 1440,
      sets: [
        { setNumber: 1, reps: 12, weight: 40 },
        { setNumber: 2, reps: 12, weight: 40 },
        { setNumber: 3, reps: 10, weight: 40 },
      ],
    },
  ],
};

// 2. Pure cardio
const cardioData: CardData = {
  date: "Saturday, Mar 15, 2025",
  duration: "1:12:30",
  totalSets: 0,
  totalReps: 0,
  volumeDisplay: "0",
  theme: "dark",
  userName: "alexfit",
  exercises: [
    {
      exercise: "Running",
      totalSets: 1, bestReps: 0, bestWeight: 0, category: "Cardio", volume: 0,
      duration: 2700,   // 45 min
      distance: 7.5,
      distanceUnit: "km",
    },
    {
      exercise: "Cycling",
      totalSets: 1, bestReps: 0, bestWeight: 0, category: "Cardio", volume: 0,
      duration: 1650,   // 27:30
      distance: 12.0,
      distanceUnit: "km",
    },
  ],
};

// 3. Mixed (weights + cardio)
const mixedData: CardData = {
  date: "Monday, Mar 17, 2025",
  duration: "1:05:00",
  totalSets: 9,
  totalReps: 81,
  volumeDisplay: "8.1k",
  theme: "dark",
  userName: "alexfit",
  exercises: [
    {
      exercise: "Squat",
      totalSets: 4, bestReps: 8, bestWeight: 225, category: "Legs", volume: 6480,
      sets: [
        { setNumber: 1, reps: 10, weight: 185 },
        { setNumber: 2, reps: 8,  weight: 205 },
        { setNumber: 3, reps: 8,  weight: 225 },
        { setNumber: 4, reps: 6,  weight: 225 },
      ],
    },
    {
      exercise: "Leg Press",
      totalSets: 3, bestReps: 12, bestWeight: 360, category: "Legs", volume: 12960,
      sets: [
        { setNumber: 1, reps: 12, weight: 360 },
        { setNumber: 2, reps: 12, weight: 360 },
        { setNumber: 3, reps: 10, weight: 360 },
      ],
    },
    {
      exercise: "Running",
      totalSets: 1, bestReps: 0, bestWeight: 0, category: "Cardio", volume: 0,
      duration: 1200,   // 20 min cool-down run
      distance: 3.2,
      distanceUnit: "km",
    },
  ],
};

// ── Light theme variants ──────────────────────────────────────────────────────
const cardioLight: CardData = { ...cardioData, theme: "light" };
const mixedLight:  CardData = { ...mixedData,  theme: "light" };

// ── Main ──────────────────────────────────────────────────────────────────────
(async () => {
  await render(strengthData, "scripts/preview-1-strength-dark.png");
  await render(cardioData,   "scripts/preview-2-cardio-dark.png");
  await render(mixedData,    "scripts/preview-3-mixed-dark.png");
  await render(cardioLight,  "scripts/preview-4-cardio-light.png");
  await render(mixedLight,   "scripts/preview-5-mixed-light.png");
  console.log("\nAll previews generated.");
})();
